### ISSUE TITLE
Unable to enchant bow with anything other than infinity in 1.12.2

### ISSUE THREAD

**Issue by wesker1213** [brandon3055/Draconic-Evolution#1025]
Using the latest version of DE. Was wondering if I was possibily doing something wrong, because I can no longer do this from the gui like we used to be able to.

**Comment by Mitchel75814** [comment]
It’s no longer done in the gui. Instead you enchant it how you normally do

**Comment by wesker1213** [comment]
That doesn't take away from the fact that I still can't put anything other than infinity on it. No power or anything like that

**Comment by brandon3055** [comment]
Just tested this in dev and everything works fine... Is it possible something in your pack is messing with bow enchants?

**Comment by Saklad5** [comment]
Most methods of enchanting don’t let you enchant items that already have enchantments. Maybe that is your issue?

**Comment by shadoxxhd** [comment]
I can enchant the bow via anvil, but the power enchantment doesn't seem to do anything. Using a not upgraded wyvern bow with maxed damage and speed I deal 12 damage to skeletons/zombies. After applying power V the damage is still 12 (they survive the first shot with 4 hearts). This might have something to do with your enchantment toggle handler, since there is no toggle option inside the bow gui.
