### ISSUE TITLE
[1.12.2] Nether and End Draconic ore lack ore dictionary names

### ISSUE THREAD

**Issue by FnordMan** [brandon3055/Draconic-Evolution#1036]
Basically the subject line says it all, there isn't any ore dictionary names for the Nether and End versions of the draconic ore, making it much harder to grab and process.

**Comment by FnordMan** [comment]
Go in game, hit f3+h and look at it, there's ZERO ore dictionary entry for the nether and end draconium ore.

**Comment by covers1624** [comment]
I believe this is intended as they should drop draconium dust. Not 100% tho.

**Comment by InterPlay02** [comment]
![lexicon](https://user-images.githubusercontent.com/23037423/35680794-7689ab4e-0742-11e8-80ed-5af79166213e.JPG)
One image worth more than 1000 words.

**Comment by Hazmatik** [comment]
![image](https://user-images.githubusercontent.com/8119393/35929704-13cbd566-0bfe-11e8-8c84-df1d37b5218e.png)
There is only one entry for oreDraconium and it's the overworld version.

And it does not change from nether or end draconium ore when you come back to the overworld, like it did in 1.7.10 versions of the mod
![image](https://user-images.githubusercontent.com/8119393/35929869-81809f06-0bfe-11e8-83a5-8b831a7de7f8.png)

**Comment by brandon3055** [comment]
This is a bug my ore registry is missing a wildcard. Regardless the most efficient way to process draconium ore is using fortune 3 or an automated block smasher that uses fortune 3.
You also get considerably more dust from the overworld and nether variants but only if you use fortune.

The ore dictionary issue will be fixed in the next release.
