### ISSUE TITLE
Question about private server making money on this mod.

### ISSUE THREAD

**Issue by Plzmtic** [brandon3055/Draconic-Evolution#1041]
Hello, i would like to ask you about one server i found, they are restricting awaken stuff from mod until you pay 20 dollars for it. If you make awaken or spawner from your mod they just disapear.
Thanks for responding

**Comment by brandon3055** [comment]
No. Even if i was ok with this which i am not it also completely violates the minecraft EULA.
If you need to restrict access to DE items then your only option is to disable them completely.

**Comment by Plzmtic** [comment]
So you might be interested in www.ftbees.com and their Crackpack server.

Im not mad or something, i just appreciate your great work on this mod from
first day i played Draco and i hate their practics.

They force players to pay 20 dollars just to play with awaken items and
spawners or play around 500 hours to get designated rank for free,
otherwise those items disapear from your inventory when you make them.



2018-02-01 4:52 GMT+01:00 brandon3055 <notifications@github.com>:

**Comment by brandon3055** [comment]
Then that server is violating mojangs eula and will probably be getting a letter from the mojang legal team at some point. I dont want servers selling access to my mod but i wont take any legal action myself because violations like this also violate the minecraft eula so mojang should take care of it for me.
