### ISSUE TITLE
Bad grammar or typo in the Draconic Axe description

### ISSUE THREAD

**Issue by BinaryCrafter** [brandon3055/Draconic-Evolution#105]
Apologies for the triviality of this issue, however there's a grammar error/typo in the description for the Draconic Axe when you hold shift when hovering the mouse over the item in NEI. It uses the word "lot's" in the description, which has an extraneous apostrophe, it should just be "lots".

**Comment by Nadermane** [comment]
Yeah, there's some of these littered around the mod. For example, in the mod's information tablet, there's lots of cases where "to" is used instead of "too". I have to admit, I'm not perfect with grammar, but I do find myself being annoyed at some of these trivial mistakes. There is also the use of capital letters in mid-sentences. Please use a quick spell checker to fix this. Shouldn't be too hard of an issue, and not really of much importance.

A slightly more pressing typographical issue is the fact that encoding doesn't seem to be working as intended in the information tablet. For instance, in most cases where the character " ' " is used, it seems to show up as " â€™ ".

Finally, I little bit of feedback about the information table is the scroll bar. More importantly, the lack thereof. I often find myself frustrated at having to scroll instead of being able to simple drag. I would like to see, once again, a scroll bar implemented.

Thanks for reading. Please know that I am never trying to offend anyone in any way, in this case spelling. I am just trying to provide you with feedback. :+1:

**Comment by GreatOrator** [comment]
The scroll bar has been acknowledged is several reports and spell-check only checks for errors in spelling, not the difference between to and too.  Appreciate the feedback for grammar mistakes and considering the volume of code and text, I am happy there aren't more of them.

**Comment by brandon3055** [comment]
Im not afraid to admit that when it comes to spelling and grammar im kinda terrible and i rely on spell check way to much. If these mistakes are really bothering people anyone can make a pull request to fix them and i will happily add it.
