### ISSUE TITLE
Server crash due to ic2 explosion

### ISSUE THREAD

**Issue by i9hdkill** [brandon3055/Draconic-Evolution#1053]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.8-279
* Minecraft Forge version: 2611
* Mod Pack: Direwolf20

## Crash report
```
https://pastebin.com/4Z9myeU7
```
Something big in ic2 exploded 
ic2.core.ExplosionIC2.doExplosion

During that a player got damaged by it and probably due to this, the server crashed:
com.brandon3055.draconicevolution.handlers.CustomArmorHandler.onPlayerAttacked(CustomArmorHandler.java:134)

But could be also a crash due to ic2, not 100% sure.

**Comment by i9hdkill** [comment]
Got another with another mod as source. Pretty sure it's Draconic now
https://pastebin.com/KRCyHpU3

**Comment by i9hdkill** [comment]
Player that are crashing the server are always in a RFTOOLS world.
Here again:
https://pastebin.com/sJGPRJQk
Hard to repdroduce, as it does not happen always. Sponge is known to cause imcompabilities, but this time it isn't sponge fault if you ask me

**Comment by covers1624** [comment]
Sponge injects code in to large portions of MC's codebase, them doing that makes it difficult to debug, for one it throws off the line numbers in the crash report so there is absolutely no way we can debug it, on top of the line numbers being moved in crash reports, we have no way of knowing if what sponge injects is the cause of the incompatability or not, you have absolutely NO basis for sponge NOT being the issue here. If someone hasnt already please report this to sponge and link the issue back here.
