### ISSUE TITLE
Texture Animation Issues

### ISSUE THREAD

**Issue by jredfox** [brandon3055/Draconic-Evolution#1067]
mc: 1.12.2

Issue: the textures are flashing without translative frames and are going to fast with that people might have seizures that could normally play minecraft so....

I suggest adding interpolation to true and slowing down the frametime.

**Comment by covers1624** [comment]
Ok.. What textures? what block / item / entity?

**Comment by brandon3055** [comment]
That look is intentional. I do understand your concern but i think if thats enough to give someone a seizure then that person probably shouldn't be playing modded minecraft because i have seen much worse than that from other mods not to mention rendering bugs.
That said that texture is probably due to be replaced so when i get to it i will replace it with something a little less flashy.

**Comment by jredfox** [comment]
Major:
draconium ore and all variants need adjustsments interpolation and slower frametime


recomendations: 
generator change frametime from 2 - 3 looks better transitions and Nothing questionable anymore about that
disloacator increase frametime by 1-2 ticks don't have to but, if you want to be safe and family freindly
increase grinder_front_active by 1 tick min looks better anyways

**Comment by jredfox** [comment]
Well tell that to my cosin then who
