### ISSUE TITLE
Draconic Bow Explosive Arrows have no delay

### ISSUE THREAD

**Issue by Yawrf** [brandon3055/Draconic-Evolution#1087]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.10.284
* Minecraft Forge version: 14.23.2.2631
* Mod Pack: (if applicable) Trident SMP

Not a crash, just a bug.
When firing the Draconic Bow with Explosion Power on (I've tested various levels), it instantly explodes, damaging me/anything immediately around me instead of what I'm shooting at. I'm not sure what's causing it, nor what other information might be relevant. Please tell me if there's anything else I should add.

**Comment by Saklad5** [comment]
I’ve noticed this in the DW20 1.12 pack, but not reliably. I wasn’t sure if this was actually the fault of the mod, since I have a substantial variety of effects from Baubles and such applied.

This also affects Shock Wave.

I’d be more annoyed if it wasn’t for the fact that both Explosion and Shock Wave are extremely impractical. Explosion because pretty much all explosions are useless (sorry TNT), and Shock Wave because it is so freaking expensive to fire that it is unsustainable even in the endgame. Especially compared to normal Auto Fire.

**Comment by Saklad5** [comment]
@Yawrf I think Auto Fire is still better for that. The explosion doesn’t reliably break it even when it hits, but a stream of arrows fired in the general direction of the hole in the Iron Bars almost always works.

A stream of arrows fired in the direction of anything usually works, actually.

**Comment by Yawrf** [comment]
@Saklad5 Lol, I wasn't even aware that arrows could go through iron bars, but I'd still prefer to bomb them, because you generally don't have time to just sit there and shoot at it while fighting the CG

**Comment by Saklad5** [comment]
They can’t. The cages around Chaos Crystals have a hole in them that you are supposed to shoot through.

**Comment by Yawrf** [comment]
@Saklad5 Ah... (I'd still prefer opening that hole a bit, but I recognize the validity of that strat)

**Comment by kiroma** [comment]
Alright so I think I've actually found a reliable way of reproducing this.
The problem here is that the explosive arrows create explosions where they were a tick before hitting a target, which when connected with the arrow speed upgrade, causes the explosions to be quite ineffective.
The explosions created by the arrows at max power are more than powerful enough to destroy the cage around the crystals, but the explosions simply happen too far away to take any effect.
The easiest way to reproduce the issue for me is to upgrade the arrow speed to Wyvern on the Draconic Bow, max it out in the config GUI, then shoot at a block <10 meters directly below you.

**Comment by kiroma** [comment]
Alright I took a look at the code and apparently this is explicitly desired behaviour.
I can't say that I agree with this design, but oh well.
