### ISSUE TITLE
Mob Souls not dropping at all.

### ISSUE THREAD

**Issue by Ledarion** [brandon3055/Draconic-Evolution#1095]
## Base information
* Minecraft version: 1.12.2
* Mod version: 1.12-2.3.10.284
* Minecraft Forge version: 14.23.2.2627
* Mod Pack: Draconic Evolution

Is NOT a crash report!
I changed the config in a multiplayer server and in singleplayer to guarentee the drop of a mob soul, but after killing hundreds of mobs with this probability of 1.00, no "luck."

**Comment by Saklad5** [comment]
[That’s an integer, not a double.](https://github.com/brandon3055/Draconic-Evolution/blob/a05bbe78970ba3d24736c94b3da2276dd5d8f86e/src/main/java/com/brandon3055/draconicevolution/DEConfig.java#L141) Try changing it to 1 instead of 1.00.

Also, make sure you changed _both_ of the config values for this. There are separate options for hostile and passive mobs.

Finally, are you using either Draconic Evolution weapons or something with the Reaper enchantment? If not, it is literally impossible for mob souls to drop, regardless of the config.

By the way, the config value is actually divided by the sum of the tier of Draconic Evolution item used and the level of Reaper enchant. If you have a Draconic Staff of Power, for instance, the default 1/1000 chance for hostile mobs to drop a soul becomes 1/**333**. If it is enchanted with Reaper V, that becomes 1/**125**.

It’s still a pain if you are specifically trying to get a Mob Soul, I admit, but it is not as bad as it might seem at first. Besides, if you are playing with another mod that can change the contents of a vanilla spawner, you don’t even need a mob soul.
