### ISSUE TITLE
When config set to hard mode, book incorrectly specifies recipe for Tier 8 Storage 

### ISSUE THREAD

**Issue by OfficialStamper** [brandon3055/Draconic-Evolution#1130]
## Base information
* Minecraft version: 1.12.2
* Mod version: Draconic-Evolution-1.12.2-2.3.12.297-universal.jar
* Minecraft Forge version: forge-1.12.2-14.23.4.2715-universal.jar
* Mod Pack: (if applicable)  ATM3

When config set to hard mode, book incorrectly specifies recipe for Tier 8 Storage

**Comment by gigabit101** [comment]
This is something that currently can not be changed.

**Comment by ouroborus** [comment]
@gigabit101 You could add a note to the book stating that Tier 8 has different requirements if hard mode has been set. You could even go so far as to have two sections for Tier 8, one for normal and one for hard.

**Comment by gigabit101** [comment]
I can't do that but @brandon3055 can :P

**Comment by OfficialStamper** [comment]
@gigabit101 Then please re-open this issue, so that it can be tracked until such time as @brandon3055 can make the change.  If you leave this issue closed, it will never get done!

**Comment by covers1624** [comment]
The documentation is in the middle of being rewritten, The documentation system DE at the moment was a proof of concept and will not be receiving any updates. DE's new documentation system has been written and documentation is being moved over, its a lot more flexible. As a result the documentation can be swapped out when the config is changed, stuff like this wont be forgotten because its being rewritten. I'm leaving this closed.

**Comment by OfficialStamper** [comment]
Received and understood, thanks for the reply.
