### ISSUE TITLE
Fusion Crafting Randomly Stopped Working

### ISSUE THREAD

**Issue by Thenlie** [brandon3055/Draconic-Evolution#1139]
## Base information
* Minecraft version: 1.10.2
* Mod version: 1.10.2-2.1.8.273
* Minecraft Forge version: 12.18.3.2511
* Mod Pack: (if applicable) Project Ozone Lite

My fusion crafting setup randomly stopped working. Nothing was changed or updated. I have tried breaking and replacing all the block. I have tried different distances for the crafting injectors but none of this seems ot work. Looks like I will be shutting my world down if I cannot get this fixed.

**Comment by brandon3055** [comment]
Can you elaborate on "Stopped Working"? You just fired up your world one day and found that recipe's don't craft? Do you still see recipes in JEI? Does the gui display anything when you have a recipe setup? Can you give screenshots?

Sorry thats just not a lot of information to go on especially given you are talking about a system that has never had any issues like the one you are describing.

**Comment by brandon3055** [comment]
Hmm... not sure.. This really shouldn't happen. The only fix i can think of would be to replace the fusion crafting core and injectors (just spawn in some replacements) and that should fix your problem. If it does let me know and keep the defective blocks because i would like to take a look at their nbt to see if i can figure out how this happened.

p.s. sorry for such a late replay.
