### ISSUE TITLE
Draconium Blocks are stackable in an EnderIO Capacitor Bank

### ISSUE THREAD

**Issue by Hypocrisy** [brandon3055/Draconic-Evolution#115]
Instead of dragging and dropping a Draconium Block in an EnderIO Capacitor Bank, if you Shift+Click you can insert a whole stack which will charge them all at the same time for the cost of just one (100M RF)

**Comment by brandon3055** [comment]
What version of DE are you using? I fixed this back in v1.0.1-RC1

**Comment by Hypocrisy** [comment]
I'm using the latest version available on your website. v1.0.1c. The same version featured on the FTB Infinity pack. I am still able to shift+click a stack into an EnderIO capacitor bank.

**Comment by brandon3055** [comment]
Ok so since the fix i implemented a while back it will actually pull the correct amount of rf for the stack size. The tool tip still says it only needs 1000000 RF but it will pull more. Throw a stack in a bank containing 100m rf and you will see it pulles all that and the stack will only be 1/64th charged.
