### ISSUE TITLE
Feature Request for 1.12.2

### ISSUE THREAD

**Issue by PegasusRider** [brandon3055/Draconic-Evolution#1152]
I don't know what the absolute max range on the Energy Relay Crystals might be, but …

Assuming that 127 is not a game limit, would it be possible to add config options to increase the range on these? More connections would be awesome, too. But that would entail a lot more programming than it would be worth, I think.

I know I could string them together if there were a playability need. Sadly it's not, it's a look/feel concern. So, no big deal if it can't be done or if you don't have the time/desire for trivialities.

Thanks for your time!

**Comment by brandon3055** [comment]
There is actually a slight technical limitation. In order to make things as efficient as possible i store the offset positions of all connected devices using bytes which do have a max value of 127. It wouldn't be impossible to change that without breaking worlds but i think i would rather just leave this for the 1.13 re write.
