### ISSUE TITLE
[Suggestion] add MFR laser drill compat

### ISSUE THREAD

**Issue by XFactHD** [brandon3055/Draconic-Evolution#116]
The MFR laser drill seems to not detect draconium ore as a valid ore to generate.
You can add draconium ore through an IMC message to the laser drill.

I could probably get something to work but I can't promise anything because I am not that good at java coding.

**Comment by GreatOrator** [comment]
Can you test using the latest build?  Additional ore dictionary entries were added that should fix this.

**Comment by XFactHD** [comment]
I can test that when I get back to my computer in some hours (It's night for me at the moment).

**Comment by XFactHD** [comment]
I tested it with the latest build and it doesn't work, neither NEI shows it nor is it actually produced.

**Comment by GreatOrator** [comment]
So the ore does not even show up in NEI?

That is odd, can you provide a screenshot?

**Comment by XFactHD** [comment]
It shows up on NEI but draconium ore doesn't show up as a "laser drill recipe" and it also isn't generated by the laser drill.

**Comment by zzApotheosis** [comment]
I can confirm the laser drill does not generate draconium ore.

**Comment by brandon3055** [comment]
Ok i will add the ore to the mfr laser drill but cant say when i will actually get around to it because i have a lot of other work to do.
 
I will leave this issue open as a reminder to myself.

**Comment by VerisZG** [comment]
Guys, minetweaker allows to add ore to mfr laser.
MiningLaser.addOre(<DraconicEvolution:draconiumOre>.weight(10)); # Draconium Ore

**Comment by brandon3055** [comment]
I did investigate adding this but in the end i have decided i will not be adding the ore to the mining laser by default. Mainly because its "supposed" to be hard to get although it really isnt once you get well established. And i dont really want to make it easier using the MFR laser.

If you want to add it yourself for your pack using minetweaker as @VerisZG suggested or by some other means i wont stop you. But im not going to add it by default.
