### ISSUE TITLE
[Issue"s"] Draconic chest

### ISSUE THREAD

**Issue by BadLucKWyvern** [brandon3055/Draconic-Evolution#1177]
Minecraft version:1.12.2
Mod version:Draconic-Evolution-1.12.2-2.3.13.306-universal
Minecraft Forge version:1.12.2-forge1.12.2-14.23.4.2757

Im using draconics chest for temporary holding stuff ready to be transformed, like bees in liquid DNA
I am putting bees manualy in the chest with the SHIFT+Click(or double click).
When holding the Shift key, when the chest is around 2/3 full (usualy with shining item) Theres a terrible FPS drop, 

The another issue, you're maybe not concerned. But Im using the inventory tweaks mod (wich allow items to be sorted in a single click) Clicking the default sort button with items in the chest only pack them, but not sorting them. The draconic chest is th lone chest wich i have that problem. Is it because the chest capacity size is too big ?

**Comment by brandon3055** [comment]
I will take a look at it but I really dont think there is much i can do about the FPS issue as thats just a side effect of having so many render intensive items being drawn all at once. 
As for the inventory tweaks issue i need to dig into the IT api a bit to see if there is a way i can fix that. 
I think the issue is more likely related to the additional crafting/furnace slots in the ui. Inventory tweaks has no way of telling whats what.

**Comment by brandon3055** [comment]
I have been looking into this and it does not look like there is much i can do. The lag im sure is just vanillas item rendering and inventory tweaks really has no way that i can find to add proper sorting support to a chest like this. I cant even move the buttons to a more convenient location.

**Comment by BadLucKWyvern** [comment]
You did what you could, that will not prevent me to play minecraft anyway,
it just was a detail
But about the lag issue, ghave you tryed with shining items? like forestry
bees ?

Le mer. 31 oct. 2018 à 15:27, brandon3055 <notifications@github.com> a
écrit :
