### ISSUE TITLE
CustomFusionRecipes not removing recipe

### ISSUE THREAD

**Issue by kilanth** [brandon3055/Draconic-Evolution#1179]
## Base information
* Minecraft version: 1.12.2
* Mod version: Draconic-Evolution-1.12.2-2.3.15.312-universal
* Minecraft Forge version: 14.23.4.2732
* Mod Pack: (if applicable) https://git.wolfrealm.org/Azureus/MakeIC2GreatAgain
Pretty much the only lines I've got in the CustomFR, the location is correct and the syntax is alright it removes anything but this particular solar, I can even add this same solar recipe. Tried also REMOVE with result and catalyst. Virtually nothing works. 
Thank you.
```
[
	{
			"mode": "REMOVE",
			"result": "solarflux:solar_panel_chaotic",
			"catalyst": "draconicevolution:chaotic_core",
			"ingredients": [
			"draconicevolution:awakened_core",
			"draconicevolution:awakened_core",
			"draconicevolution:awakened_core",
			"draconicevolution:awakened_core",
            "solarflux:solar_panel_draconic",
			"solarflux:solar_panel_draconic",
			"solarflux:solar_panel_draconic",
			"solarflux:solar_panel_draconic"
        ]
	}    
]
```

**Comment by brandon3055** [comment]
I have a feeling this is due to mod loading order. DE is getting called to register recipes before Solar Flux so when the json is read that recipe has not been added yet. In the next update i will move the json loading to a later event which should fix this issue. 

Im not sure when i will push the next public release but in the mean time i have a dev build you can use to test the fix. http://chickenbones.net/maven/com/brandon3055/draconicevolution/Draconic-Evolution/1.12.2-2.3.15.313/

**Comment by kilanth** [comment]
Thank you, good sir, dev builds are always questionable, no offense. I better wait for the release, thanks for the reply!

**Comment by brandon3055** [comment]
Umm... No? What?

The only difference between that build and a released build is i have not pressed the magic button that pushes it to curse. The reason being i dont like spamming curse with countless builds that fix minor issues. Instead i wait until ether i have enough changes for it to be worth pushing a new release or i may push a release if it fixes a serious issue.

The primary reason i gave you that build is so you can confirm the issue is fixed **Before** i push a new public release.

**Comment by kilanth** [comment]
Dev build version has resolved the issues, thank you!
