### ISSUE TITLE
[Suggestion/Feedback] Keep the vertical speed boost separate from flight speed

### ISSUE THREAD

**Issue by IndubitablyLeft** [brandon3055/Draconic-Evolution#1181]
## Base information
* Minecraft version: 1.12.2
* Mod version: 3.15.312
* Minecraft Forge version: 14.23.4.2762

Skyfactory 3 (2.1.6.263) has an older version of DE which has the flight speed modifier separate from vertical speed. In recent versions the two have been merged, which I find undesirable.

Vertical speed normally is agonisingly slow and I like to have a hefty boost to that, but now that these two are on the same slider this means I can't do that without also increasing my horizontal speed much more than I like. This is especially noticeable if one engages flight lock, even a small tap of WASD will send the player flying (I know sneaking would temporarily disable that, but it would be nice not to have to hold down a key all the time).

**Comment by brandon3055** [comment]
This is something that i have been meaning to look into. The issue is flight speed is modified by modifying the player's flight speed attribute but as you can see that effects flight in all directions. I switched to this because its much cleaner than the hack i used to modify speed in 1.7 but it looks like it may take another hack to give you independently adjustable speed settings.

Keep in mind you can also use the "Boost on Sprint" option to only boost your speed when you press your sprint key.
