### ISSUE TITLE
Baby Zombie Pigman Without AI

### ISSUE THREAD

**Issue by LucunJi** [brandon3055/Draconic-Evolution#1187]
## Base information
* Minecraft version:1.12.2
* Mod version:1.12.2-2.3.13.306
* Minecraft Forge version:14.23.4.2759
* Mod Pack: (if applicable)

## Issue report
Stable Spawner will spawn Baby Zombie Pigman Without AI. These zombies will float in the air and do nothing. They still takes up the mob limit.
These baby zombie pigman will disappear after reloading the save.

**Comment by brandon3055** [comment]
The fact that these mobs disappear when you reload tells me that they are client side ghost entities (they dont actually exist on the server) Im not sure exactly what could cause this because DE is very careful to avoid things like this and i can not reproduce this issue. I suspect some mod is doing something weird when pigmen spawn. Perhaps spawning additional baby pigmen but without the proper checks to prevent spawning client side mobs.
