### ISSUE TITLE
[SUGGESTION] Quick-switch settings for the Draconic Staff of Power

### ISSUE THREAD

**Issue by Nova001Sol** [brandon3055/Draconic-Evolution#12]
Here is a suggestion I feel the Staff would benefit from. Basically, I'd like to see a way to set two or three different modes for the Staff that can be set independently but can be switched between without too much effort. For example, say I'd like to the Staff for making tunnels, for precision mining and for ripping huge sections of the world apart instantly. With multiple modes I would be able to set mode A to dig 1x1x1 with decreased speed. Mode B would be 3x3x1, increased speed, and mode C would be set to 9x9x9, default speed. If I could just use right-click to switch that would save me a lot of effort to alter my settings every time.

**Comment by brandon3055** [comment]
Hmm... I do like the idea. I may look into it once i finish my current project.

**Comment by GeneralAtrox** [comment]
Im in full favour of this idea. I've accidently taken a good 9x9 chunk out of my base by attempt to break machinary and the like by accident. Due to the instant dig, there is no chance of stopping it. 

Perhaps a mode to stop it auto-digging player made blocks/machinary should be added along with the Void Junk etc...
