### ISSUE TITLE
Draconic Bow unable to fire while charging

### ISSUE THREAD

**Issue by douglasg14b** [brandon3055/Draconic-Evolution#1200]
## Base information
* Minecraft version: 1.12.2
* Mod version: 1.12.2-2.3.15.312
* Minecraft Forge version: 14.23.5.2768
* Mod Pack: ATM3

If the draconic bow is charging (ie. wireless charger) while you are trying to use it, your character seem to be able to hold it (the bow does not appear on screen). And when trying to fire, it rapidly  appears and disappears from view and does not fire.

It may flash into and out of view while charging as well. But it mostly unusable until charged, or charging stops.

The bow will fire if quickly clicked, but cannot be drawn back.

**Comment by drunkripper** [comment]
https://youtu.be/eeYYemaVqeA
Unable to repeat issue with same mod version.

**Comment by andrelec1** [comment]
I have same issue, but not only on the bow ... every tools that have RF.
so, I think is not DE fault...

In fact it seem the bow is not charged, but replaced by a copy of it with more rf in ...

My first thought is EnderIO ... but really need testing!

**Comment by douglasg14b** [comment]
Yeah, I'm getting this for every tool that uses RF as well ow that you mentioned it.

I'm not quite sure of how to test this to figure out why.

**Comment by drunkripper** [comment]
My best guess would be the fact the item changes when it's charge level changes. i haven't checked the code yet but i'm assuming that @brandon3055 uses the MinecraftDurability as a display.

**Comment by andrelec1** [comment]
i can't say ...
I realy think this is not a DE fault ...
Like i say,  it seem the bow is not charged, but replaced by a copy of it with more rf because i have this issue with other mod too ...

**Comment by douglasg14b** [comment]
Ah jeez, stalebot here too hu?

**Comment by FoxMcloud5655** [comment]
Yes, because it's an old issue that needs to be closed down since there hasn't been any replies for literal years.

**Comment by douglasg14b** [comment]
If the problem is resolved or just doesn't exist any more then it should definitely be closed!

Though I fail to see how the age of an issue can be the sole function of it's validity, as you are implying.

**Comment by FoxMcloud5655** [comment]
Sole?  No.  But the fact that it's lasted for 2 years without anyone saying anything about the issue confirming it or denying it certainly speaks to how irrelevant it is now.

Issues like this are marked as stale usually due to an issue that was likely fixed by a Forge update, fixed by a DE update and never marked as fixed, it being a mod incompatiblity issue that was silently solved on the other side, or it being such an uncommon issue that most players can't even replicate it due to either how the bug works (like a race condition) or how hard it is to trigger the bug.
