### ISSUE TITLE
Crashing With Custom Modpack

### ISSUE THREAD

**Issue by robbooooo1234** [brandon3055/Draconic-Evolution#124]
Hey guys, so i have seen people using this mod on the hermitcraft FTB Infinity series and i have a custom modpack (originally Crackpack 2) that has lots of mods and in FTB Infinity there are alot of the mods im using in my custom one. so i just added it and i get a crash just as its about to load up the main screen. i have tried installing older versions of this mod but no luck. is there anyway way i can use this mod in my custom modpack? if not what mods do i have to remove to be able to use this? this crash report is here: http://pastebin.com/sttvCZX8

**Comment by brandon3055** [comment]
Looks like a simple enchantment id conflict. DE uses id 180 for its reaper enchant by default but it looks like something else in your pack is already using that. Just change that to an unused id (may need to try a few until you find one) and it should work just fine.

You can also start the game without DE and use NEI to get a list of all available enchant id's Go to the NEI options menu>Tools>Data Dumps and dump the free potion id's That will create a text file containing all the free potion id's. Make sure you set it to dump the free id's because by default it will dump the used id's.

**Comment by robbooooo1234** [comment]
and where can i change the ID from?

**Comment by robbooooo1234** [comment]
okay found it, thank you so much! it works great :) and thanks for making such a good mod :D
