### ISSUE TITLE
Draconic Evolution cause crazy chunk update

### ISSUE THREAD

**Issue by hotarunso31** [brandon3055/Draconic-Evolution#1247]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.18.329
Minecraft Forge version: 14.23.5.2768
 Mod Pack: No (w/ Optfine, Foamfix)
OS: Debian 9

It is not a crash but an annoying problem. Normally, the Minecraft seldom do chunk update when I stand and do nothing. After I install your mod - Draconic Evolution, chunk update occurred every time. The times of chunk update showed in F3 screen always remain 89 then 97 and again .... This make Minecraft use very high CPU usage even when I pause the game! When I removed it, the cpu usage becomes normal again (~67%-87%). 

Why the chunk update happened? I really want to keep this awesome mod!

**Comment by brandon3055** [comment]
Are you sure this is DE? I dont have this issue in my test world. Chunk updates occur when a a block needs to be re rendered. This is happens when breaking and placing blocks. It also happens when some blocks need to update their texture. e.g. a furnace switching from off to on or more notably things like redstone. A simple redstone clock will cause continuous chunk updates. I suggest you look around your base and try to figure out what block/blocks are causing the updates because simply installing DE would have no effect on chunk updates. Also keep in mind some amount of chunk updates are normal. The issues come when the chunks being updated contain a lot of complicated blocks to re render.

**Comment by ben-mkiv** [comment]
Does it maybe retrogenerate draconium ores which could cause the updates? If so it should settle after some time.
