### ISSUE TITLE
Wrong output on Tier 7 Energy Core

### ISSUE THREAD

**Issue by AragurLP** [brandon3055/Draconic-Evolution#125]
If you wrap the Peripheral with ComputerCraft you get returned wrong output (getMaxEnergyStorred or getEnergyStorred)

**Comment by Ianaver** [comment]
@AragurLP first of all, "stored" has only one "R" not two! :P

**Comment by AragurLP** [comment]
Sry, wrote it false. Of course I wrote it with 1 "R"

**Comment by Ianaver** [comment]
ok, sadly bc I am not familiar with computercraft yet I won't test this yet

**Comment by AragurLP** [comment]
Tomorrow I can test it, what excactly the problem is and I also will deliver screenshots.

**Comment by XFactHD** [comment]
@AragurLP As far as I know the problem is that ComputerCraft uses a 32bit architecture and the number that the energy pylon is providing is too long / to high to be saved in a 32bit value.

**Comment by AragurLP** [comment]
So it's a Computercraft "Bug"?
Vor is there a way to fix it?

**Comment by XFactHD** [comment]
It's not a bug, it's a limitation for the sake of compatibility. If ComputerCraft would use a 64bit architecture, you couldn't use it on a PC with a 32bit OS. There are as far as I can think of two solutions: dan200 releases a 64bit version of CC (which I doubt he would do because it would end in a disaster) or @brandon3055 changes the way the energy values are provided to CC. I will look at the code, perhaps I can come up with a solution.

**Comment by brandon3055** [comment]
Close. But its actually just a limitation of the RF API which handles all of its values as integers. At some point a will be adding computer craft integration so that the pylon will be a custom peripheral which allows you to read the full amount of stored energy. (Computronics has already done this)

**Comment by martmists** [comment]
It's been two years, and I'm still having this issue. Even when the energy stored is not maximum, it is still reported to be. (2147483647 or 2^32-1) Has there been a fix yet?

**Comment by brandon3055** [comment]
This will never be fixed because it is an unavoidable limitation of the RF API. If you are using a computer then use DE's energy peripheral interface.

**Comment by martmists** [comment]
Is that peripheral interface available in 1.7.10? I don't think I was able to find it. (The reason I'm using 1.7.10 is because we're running a custom modpack, made specifically to use mods we like which include discontinued ones)

**Comment by brandon3055** [comment]
Yes you need to connect the computer to a pylon. The peripheral name is 
draconic_rf_storage
It has the following methods.
getEnergyStored and getMaxEnergyStored
