### ISSUE TITLE
particle generation Error

### ISSUE THREAD

**Issue by SteamDoge9000** [brandon3055/Draconic-Evolution#1252]
#### Issue Description:
Particle are not working correctly

#### What happens:
when the particle generator is used along with the particles that come from the shockwave and the draconic energy storage they apear to be ether grey or missing

ex; Set particle generator to emit Red 255 particles
particles generated are grey

#### What you expected to happen:
For the correct colors to be produced and for the apropate colors to appear from the pylons pulling and emiting Rf into the energy core

#### Affected Versions (Do _not_ use "latest"):
* Minecraft: 1.12.2
* Forge: lattest _for me_ (14.23.5.2807
* Crafttweaker: 1.12-4.1.13
* ModTweaker: not Present
* MTLib: not Present

#### Your most recent log file where the issue was present:
https://gist.githubusercontent.com/SteamDoge9000/6ecffbf05c8d4cd06c4721e82833f6d6/raw/76368db1c93996cd23e0c555759b08224cbc08a3/Gaamelog
(this is the full file due to tucking)

**Comment by SteamDoge9000** [comment]
narrowed down the mods into this Twitch pack

[s-1.0.zip](https://github.com/brandon3055/Draconic-Evolution/files/2873480/s-1.0.zip)

**Comment by SteamDoge9000** [comment]
possable conflict with Techguns

**Comment by SteamDoge9000** [comment]
it aperes to have been caused by the custom effects of a mod known as Techguns for 1,12,2

**Comment by brandon3055** [comment]
Did some digging and it looks like Techguns is breaking the particle render state. They are enabling GLLighting for their particles and then not disabling it when they are done. This breaks most other particles that render after techguns because most particles render with lighting disabled. I will have a fix for this in the next Brando's Core release but you should also open an issue on the Techguns github.
