### ISSUE TITLE
OreDict names for nether/end ore variants

### ISSUE THREAD

**Issue by Rongmario** [brandon3055/Draconic-Evolution#1258]
https://github.com/brandon3055/Draconic-Evolution/commit/9374459a2f03b4c2ef04125c45e2230d71837352 removed nether/end ores being registered in the OreDictionary. 

I understand the concern, but I'm sure its possible to name them ore * dimension * name (oreNetherDraconium, oreEndDraconium) since mods such as GregTech and EnderIO respect that?

**Comment by FoxMcloud5655** [comment]
I can actually respect that.  This would allow other machines (like Mekanism's Digital Miner) to still be able to reference that specific ore by name instead of by a specific ItemStack.

**Comment by brandon3055** [comment]
It really does not make a lot of sense to use those names. Sure the ore dict **can** be used by things like the Digital Miner for the purpose of identifying ores but that is only a small part of why the ore dictionary exists. Its primary purpose is to define separate items from separate mods as "the same" So Copper ore from mod A and copper ore from mod B are interchangeable and work with all other mods. That is the primary purposes of the ore dict. 

The other thing it does is allow you to find different forms of a resource. e.g. oreDraconium > dustDraconium > ingotDraconium. Thats really useful because if you need to find an ingot for an ore you just replace "ore" with "ingot" and bingo your guaranteed to find the ingot for that ore if it exists.
Adding something like oreNetherDraconium takes that well organised system and throws a giant wrench into it because there is no dustNetherDraconium or ingotNetherDraconium.

So thats my reasoning for this change. Hopefully now you see why this is a bit of a tricky situation for me to deal with. At this point im considering side stepping this entire issue by making the ores equivalent and increasing the cluster size in the overworld and the end. So they would still be as rare but you would find a much larger cluster instead of just one or two pieces.

**Comment by Rongmario** [comment]
Hmm from my cases of EnderIO and GregTech, that is not what would happen, when oreNetherDraconium gets processed, it either gives (in EnderIO's case):

- oreDraconium * 2
- netherrack output

or GT:
- dust/crushed/impureDraconium
etc.

It does not also stitch on the dimension name onto product of processing.

**Comment by brandon3055** [comment]
But those mods would have had to specifically add support draconium ore or ores like it which means the ore name is irreverent in that case.

**Comment by FoxMcloud5655** [comment]
I do see why, now.  My apologies.
