### ISSUE TITLE
Reactor Explosion Crash with MFFS

### ISSUE THREAD

**Issue by Prang97** [brandon3055/Draconic-Evolution#1266]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.18.329
* Minecraft Forge version: 2768

The game crashed as soon as the explosion countdown ended, no visuals from the explosion occurred, just the crash. 
MFFS was set up around all parts of the reactor, underneath it, advanced cube module. 
Creative sandstone world

## Crash report
```
Report with MFFS: https://paste.dimdev.org/avifoyexux.mccrash
Report with Brandoncore: https://paste.dimdev.org/etunahajoq.mccrash

**Comment by FoxMcloud5655** [comment]
According to the crash report from Draconic Evolution, this line of code was in the middle of trying to execute when the game crashed:
```
randOffset = Minecraft.getMinecraft().world.rand.nextInt(3265324);
```
That probably means that it's not DE's fault; it's whatever other mod is implementing the MFFS.

**Comment by brandon3055** [comment]
The second crash should not have been possible but regardless it will be fixed in the next update.
The first crash looks like something i have had to deal with meany times in DE. Its something that would have to be fixed in MFFS. Dont ask me how but its possible for a tile entity to exist without the block it belongs to. So the tile tries to modify its block but instead it ends up trying to modify air which causes that crash.
