### ISSUE TITLE
Bug/Crash Mob Grinder game crash.

### ISSUE THREAD

**Issue by SirAron111** [brandon3055/Draconic-Evolution#1290]
## Base information
* Minecraft version:1.12.2
* Mod version:Draconic-Evolution-1.12.2-2.3.20.333-universal
* Minecraft Forge version:1.12.2 - 14.23.5.2825
* Mod Pack: (Dimension Zero)

Found this or similar crashes with various other things seem to happen anytime anything targets the grinder or targets it on revenge and cant applies the dmg or something.

## Crash report
```
https://pastebin.com/pAeqmZ1p
```
Please note assuming the issue is a crash something like this

```    at com.brandon3055.draconicevolution.blocks.tileentity.TileGrinder.updateGrinding(TileGrinder.java:130)
    at com.brandon3055.draconicevolution.blocks.tileentity.TileGrinder.func_73660_a(TileGrinder.java:55)```

Is NOT a crash report!</br>
Attach the crash report as a txt file to your issue or use a link service like pastebin.</br>

I need the full crash report which you can find in the crash-reports folder in the minecraft folder.</br>
Failing that please give me your entire minecraft log from the session when the crash occurred.</br>
If you do not provide these your issue will be insta-closed.

**Comment by SirAron111** [comment]
K I added this to the report i did on that page. (But inst there away to make even if there is a fake player just makes the block somehow immune or untargetable? It’s not funny if it gets mounted by silverfish or skeletons keep shooting arrows at it. Until some mod crashes it like Eblobs wizards with spells or champions with affixes.) It’s the same with the industrial forgoing mob crusher. Isn’t there away to improve the fake player on fore? I myself have no idea about modding so I can only ask and report things if I find them sry.

**Comment by brandon3055** [comment]
Not really. For the most part fake players work just fine. Most of the default player functionality is disabled to prevent issues like this but there is only so much forge can do from their end. All mods need to do is a simple "is fake player" check and done of these problems would occur.

The issue in this particular case is that when a player attacks a certain mob champions steps in and does some unusual stuff. It gets the source of the damage and if that source is a player it tried to add a potion effect. Thats fine if its a regular player but with a fake player that causes a crash. Technically this particular crash could be fixed by forge if they just modified their fake player to ignore the application of potions but there are so many edge cases like this that they really cant fix them all. Mod devs just need to be aware that fake players exist and check for them (Which most mod devs do)

**Comment by SirAron111** [comment]
Sounds very reasonable! Thx champions mod dev said the same (as you can see if you go on the linked problem page above) that rough mobs needs to check for fake players. Well will see the only mod dev that didn’t respond yet was from rough mobs.
