### ISSUE TITLE
Spawner Blacklist

### ISSUE THREAD

**Issue by LCAdmin** [brandon3055/Draconic-Evolution#131]
I'm having a little issue with the Spawner blacklist. It doesn't appear to work. I saw the default: part in the explanation, which makes me think I need to include the mod, but the examples given seem to say otherwise. Here's my config: http://pastebin.com/2iMXcwL6

**Comment by brandon3055** [comment]
Im not sure what happened with the description for that config option... What it actually dose is prevent the listed mobs from dropping their souls. But it will not delete existing souls of that type and it will not stop spawners of that type from working. I will fix that in the next version so that existing spawners of that type will not spawn. 
Also the name you need is the name that shows in the tool tip of the soul for the mob you wish to blacklist.
