### ISSUE TITLE
Creative Exchanger attempts to copy blockstate data to other blocks that don't have the exact data

### ISSUE THREAD

**Issue by Cynosphere** [brandon3055/Draconic-Evolution#1319]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.21
* Minecraft Forge version: 14.23.5.2836
* Mod Pack: Enigmatica 2 Light

## Crash report
https://mystb.in/ebuwibafaj.txt

This was done on a server, and any attempt to reset the player data still caused the player to crash when they reconnected.

**Comment by brandon3055** [comment]
Im not exactly sure how this is possible. The exchanger stores the block registry name and metadata. it then retrieves the block from the registry and requests the blockstate from from that block. So the only way this could occurs is if the block returns an invalid state.

Also the player should not crash when they login again. That would suggest the server has invalid block states which should be impossible because that would crash the server.

Can you show me the crash that occurs when the player logs in again?
Also does restarting the server fix the issue?
