### ISSUE TITLE
mobs stuck midair

### ISSUE THREAD

**Issue by sosa1996** [brandon3055/Draconic-Evolution#1339]
## Base information
* Minecraft version: 1.12.2
* Mod version:2.3.23.345
* Minecraft Forge version:14.23.5.2836
* Mod Pack: Enigmatica 2
my spawner "wyvern core" it keeps spawning baby zombie in mid air and they stuck and stop the spawner form working

**Comment by FoxMcloud5655** [comment]
First of all, is this on a server or is this on your own PC that this is happening on?  If this is on your personal PC, would you mind providing the latest.log file from when this was happening?

**Comment by sosa1996** [comment]
its form a server

**Comment by FoxMcloud5655** [comment]
I'm going to guess that this server is running Sponge.  In `/config/brandon3055/DraconicEvolution.cfg`, change the variable `B:forceDroppedItemOwner=true` to `false` and restart the server.

**Comment by sosa1996** [comment]
did that same problem after 20 mins or so the spawner start spawining them

**Comment by brandon3055** [comment]
Do you know if the server is running Sponge?
I believe Sponge will freeze entities if they are a certain distance from the player. It should then unfreeze them when you get close enough but sponge does have a habit of breaking in weird ways.

**Comment by jeremiahwinsley** [comment]
I am running version 2.3.24.349 in the FTB Academy modpack and I have this issue. This is on my server running standard Forge, not Sponge. I have a Stabilized Spawner with an Awakened Core, and the baby zombie pigmen get stuck in the air (the adults are fine). I can kill them and they drop loot, but they respawn after some period of time. If I use a "Mob Imprisonment Tool" on them, it will act like it collected a mob, but will not remove the original mob and doesn't place a mob when used again. Let me know if I can provide any other information.

![spawner](https://user-images.githubusercontent.com/7946299/70288692-68e0f180-17a0-11ea-8845-4f8755f27ae8.png)

**Comment by FoxMcloud5655** [comment]
That sounds like the client spawning a mob when the server says it's not really there.  Just my 2 cents.

**Comment by brandon3055** [comment]
That is exactly what's happening. The issue is that is not possible. The spawner spawns the mobs server side then the server syncs the mods to the client. My guess is that something else is stepping in after the mob spawns and removing it without updating the client properly. I have no way to fix this without knowing whats causing it. And even then it may not be something i can fix from my end. 
If you have creating access try reproducing this with a vanilla spawner.

p.s. You can set a vanilla spawners type with a spawn egg.

**Comment by Serega007RU** [comment]
Although the author of the mod no longer supports 1.12.2, but I'm just bringing it to your attention, this is because of what, the Pig Zombie spawns being riding on a chicken. The author of the mod just won't spawn this chicken and that's how it turns out that a zombie is hanging in the air, minecraft thinks he's sitting on a chicken, and the chicken still doesn't exist.
