### ISSUE TITLE
Transceiver effects not rendering sometimes.

### ISSUE THREAD

**Issue by ruifung** [brandon3055/Draconic-Evolution#134]
Only in this area shown though, if I go away from it, the effects show. So I think it's something in this area causing it.

![2015-08-06_21 42 58](https://cloud.githubusercontent.com/assets/1073945/9112967/a717045e-3c84-11e5-8611-8da2f0293230.png)

**Comment by brandon3055** [comment]
Only thing i can think of is maby you are exceeding the particle limit (because those effects are actually particles). Are there a lot of particles in that area? you can check how many particles currently exist within render distance by pressing F3 and the particle count is shown as "P:" if that is at 4000 then you are exceeding the limit. 

In ang case i am going to be making some changes to those in the future which should fix any issues like this.
