### ISSUE TITLE
Disable FOV warp not working in (spongeforge) Mutiplayer server

### ISSUE THREAD

**Issue by B-Knight49** [brandon3055/Draconic-Evolution#1364]
## Base information
* Minecraft version: 1.12.2
* Mod version: 1.12.2-2.3.24.349
* Minecraft Forge version: forge1.12.2-14.23.5.2838 \\ spongeforge-1.12.2-2838-7.1.7-RC3924
* Mod Pack: [Royal Goliath](https://www.technicpack.net/modpack/royal-goliath.1537496) (Custom made by me and some friends). 

## Crash report
No crash information available. I can provide server logs and client logs if required, please don't auto-close the issue. This is (obviously) not causing a crash but is an issue nonetheless - one that I imagine won't show anything in logs. 

## Additional information
I currently have TechGuns, Numina and EnderIO installed which each have their own FOV speed hack. I've disabled the hacks for TechGuns and Numina in their respective .cfg files, nothing is configurable for EnderIO though.
The Disable FOV Warp option *works in singleplayer* with all other FOV hacks enabled *AND* disabled. Makes me wonder if it's a SpongeForge compatibility issue.

**Comment by FoxMcloud5655** [comment]
It could quite possibly be. To be clear, you are talking about the FOV warp that the armor specifically gives and no other FOV changes (Speed III potion effects, etc.), correct?

**Comment by B-Knight49** [comment]
Yes, just the armour. No other effects were applied and no other FOV changes at all. It's just the FOV change from the Draconic/Wyvern leggings when the speed modifier is increased - and, again, only in multiplayer. Singleplayer, the FOV fix (built into this mod + Numina) works perfectly and even on the highest speed setting, the FOV is what I set it at in the video settings.

**Comment by FoxMcloud5655** [comment]
I'm inclined to agree with you.  Unfortunately, I haven't the foggiest clue about SpongeForge and it's compatibility with mods, so I'll leave this to the experts.

**Comment by B-Knight49** [comment]
I'm by no means an expert but I recently opened an issue for another mod that was the result of it lacking SpongeForge compatibility. It seems that Sponge does some patching and editing behind the scenes that can mess up other mods. If that's of any help... 

Nonetheless, thanks for looking into it.

**Comment by brandon3055** [comment]
FOV modification is an absolute pain in the ass. There is no way to properly fix one thing without breaking ten other things so i settled on a compromise that works in 'most' situations. 
It sounds like your saying the issue is there isn't enough FOV warp? If so that is intentional. By default at max speed your fov is ridiculous. 
But i will add a config option to disable my FOV correction if that helps.

**Comment by B-Knight49** [comment]
No no no, the issue was the "prevent FOV warp" feature was not working as intended. In other words, the FOV was fucking atrocious and sometimes felt like it was hitting 180 degrees. The warping caused by the increased speed was crazy. 

Weirdly, the "prevent FOV warp" feature was working fine in singleplayer and my FOV was ~90 the entire time even at the highest flying speeds. In multiplayer (on SpongeForge) this was not the case and my FOV would go from ~90 to, again, absurd values where I could actually start seeing the world unrender in my peripheral vision.

**Comment by brandon3055** [comment]
The fact that this isn't an issue in single player / without sponge is rather confusing. The FOV warp effect should be entirely client controlled. My best guess is SpongeForge it modifying the underlying system that controls player movement speed in such a way that breaks the client side fov update event which mods use to control fov. If that's the case there may not be a way to fix it from my end.

There is one way to find out. Try running this on your client. [https://ss.brandon3055.com/caa2e](https://ss.brandon3055.com/caa2e) Its just a random test mod that does a few useful things. One of which is restrict your maximum FOV to 120 degrees. It's event is set to lowest priority so it should have last say. Unless your issue is caused by another mod that is also set to lowest priority. In that case it just comes down to mod loading order.

**Comment by B-Knight49** [comment]
That fixed the warping nicely, yeah. Made it act like it would in Singleplayer. I hope that helps.
