### ISSUE TITLE
scrolling long dislocator list changes selected location

### ISSUE THREAD

**Issue by Spongman** [brandon3055/Draconic-Evolution#1376]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.24
* Minecraft Forge version: 14.23.5.2846
* Mod Pack: (if applicable) FTB Academy

to repro:
- have more than 12 locations in your advanced dislocator list
- left-click the top location to select it / make it the default
- scroll the list down (either using the mouse scroll wheel, or the list's arrow buttons) 
- scroll the list  back up
- bug: the selection has changed

this is really annoying, as it means that if you have the first item as youe home/default location, and you then dislocate to the last item in the list, you have to go back into the UI to set the default location back to what it was before. every time.

**Comment by brandon3055** [comment]
This is technically not a bug. Due to the way the dislocator is written the selected item must be within the displayed items. 
The dislocator is due for a complete rewrite.

**Comment by Spongman** [comment]
not a bug? you mean it's supposed to be broken like that?

**Comment by FoxMcloud5655** [comment]
That's correct.  Due to the limitations of how the dislocator works GUI-wise, this is how it works.  It's not that it's a feature or a bug, just that it's an unfortunate side effect of how the GUI was coded.

Ideally, the list elements would all be rendered, then the ones not constrained by the outside bounds of the GUI would be temporarily disabled, then would be procedurally turned on/off as needed to render the list.  That still requires a lot of time to implement, so it might as well be a complete rewrite since it needs it anyways.
