### ISSUE TITLE
Creative mode players are killed by the chaos dragon

### ISSUE THREAD

**Issue by Joeppie** [brandon3055/Draconic-Evolution#1379]
Insta-close it if you want, but I just deleted a server game because of the chaos' dragon's "void damage" bypassing creative mode.

This to me is something that immediately ended all interest in continuing to play this mod, and you should consider a flag that disables that. Lacking that, I have zero interest in ever playing this again, or even recommending others playing this.

This is just not a good "feature" at all, and even if some enjoy this "feature" to me, and probably many others, it is an absolute nightmare and disaster.

**Comment by FoxMcloud5655** [comment]
It is designed this way on purpose.  In the code, there's a specific flag that foils invulnerability to stop players from cheesing it.

For the sake of your argument, I agree that it should be a config option, and it probably wouldn't be too hard to add.

**Comment by sh4ni** [comment]
The whole point of "cheesing" it is completely useless if I can just give myself as many Chaos Shards as I wan't if I have Creative Mode anyway. Please consider this.

I managed to farm them pretty good without cheats whatsoever but now there are 2 Chaos Dragons on one Island for whatever reason. So consider this as a bug.

My problem now is: I'm not able to kill 2 of them at the same time. They spawn those heal beacons all the time very fast and I have no way to get my stuff back. The only way I see is to edit the map with MCEdit or something. It's just stupid if you can't fix something like that with admin commands.

**Comment by FoxMcloud5655** [comment]
I don't think you get what I mean by my first point.  Foiling invulnerability to prevent cheesing of the Chaos Guardian is something that was added because survival mode players, using some mods, can make themselves invulnerable.  The side effect of this is that creative mode players are also damaged by the projectiles.

I used to be the director for a sizable Minecraft community.  If I really needed to get in there and save someone's stuff, not only was there 2 different grave mods that can restore someone's inventory forcefully, but I also could go in there with fully upgraded Draconic armor and a creative flux capacitor.

As for the multiple Chaos Guardians, I have had that happen in one of my playthroughs too, but I have no idea how it was triggered.  If you feel like killing the both of them is too hard, there is a config option that prevents Chaos Guardians from regenerating their crystals.

**Comment by sh4ni** [comment]
Getting the stuff back is not the problem, I just like to keep my map clean and I see no other way then deleting the chunks and let them regenerate.

But normal players without admin privileges have basically no way to get their stuff back.

But there should be a way to detect if a player is in creative mode or if they are invulnerability by their armor.
