### ISSUE TITLE
Visual bug?

### ISSUE THREAD

**Issue by Cypher121** [brandon3055/Draconic-Evolution#138]
My whole energy system started looking differently and I can't find anything in the changelog about it. Is it normal? If not how do I fix it?
![2015-08-14_17 44 02](https://cloud.githubusercontent.com/assets/8020624/9274142/845d0c32-42ac-11e5-8445-b737cf264751.png)

Update: It disappeared after I went away and returned.

**Comment by brandon3055** [comment]
This is most likely due to an error to another block's renderer which makes it kinda tricky to track down. It may be the energy infuser which is fixed in the next version. For the rendering error to show that block that is causing the issue needs to be placed/loaded after the block that is being effected. When you went away and came back the energy network was probably the first thing to load making it appear as if the issue went away but it will probably be back. Unlock this thread if you find out which block is causing the issue.
