### ISSUE TITLE
cyclink staff profiles doesn't enable/disable silk touch

### ISSUE THREAD

**Issue by Spongman** [brandon3055/Draconic-Evolution#1384]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.23.349
* Minecraft Forge version:
* Mod Pack: FTB Academy

enchantment config is confusing/broken.

in the tool config dialog it says "Allows you to deactivate/activate a previously applied enchantment. Note this setting is not profile specific meaning you cannot have different profiles with different enchantment settings."

Apart from the 2nd sentence not being proper English, it's clearly wrong, because you _can_ have different profiles with different enchantment settings: you can change the setting in one profile, and as you rotate through the profiles it shows the 'On/Off' indicator changing for the enchantment settings.

And it seems that if you do this (have different profiles with different settings) then it randomly breaks the various enchantments. for example: i can no longer get my fortune iv enchantment to work. the DE tooltip shows it's enabled, the inventory tooltip shows the tool has the enchantment, but when i break a block it uses silk-touch instead, even though that is disabled and doesn't show as enabled in any of the tooltips.

**Comment by FoxMcloud5655** [comment]
Please explain why the second sentence isn't proper English.  It makes perfect sense to me.

The enchantments being "turned" off and on through different profiles is not really happening.  Due to the way Minecraft handles enchantments, it makes it difficult to switch on the fly.  Please only make your changes to the enchantments when you open the config GUI, not per profile.
