### ISSUE TITLE
Hello I cant not use the injectors 

### ISSUE THREAD

**Issue by toshimiman2004** [brandon3055/Draconic-Evolution#1497]
hello I can not use the injectors in any way, even putting the energy crystals and transfer of the mod and I tried to use the mekanism cables
## Base information
* Minecraft version:1.12.2
* Mod  version: 1.12.2-2.3.27.353
* Minecraft Forge Version:8.0.99.99
* Mod Pack: bibliocraft 
* Biomes o’plenty 
* Chisel 
* Power gems 
* Larga ore deposits 
* Ctm 
* Jei 
* Chop  down 
* Chunk loaders 
* Thermal fundation,cultivation and dynamics  
* Flux networks 
* Iron furnaces 
* Jorney map
* Mantle 
* Mekanism Generators and tools 
* Roguelike dungeons
* Simple storege network 
* Travelers backpack 
* The twilight forest 

## Crash report
```
CRASH REPORT HERE
```
Please note assuming the issue is a crash something like this

```Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Some Mod```

Is NOT a crash report!</br>
Attach the crash report as a txt file to your issue or use a link service like pastebin.</br>

I need the full crash report which you can find in the crash-reports folder in the minecraft folder.</br>
Failing that please give me your entire minecraft log from the session when the crash occurred.</br>
If you do not provide these your issue will be insta-closed.

**Comment by FoxMcloud5655** [comment]
First of all, your Minecraft Forge version is either from a mod repost site or it's unofficial, as the 8 series (currently 8.9.0.775) is for Minecraft version 1.6.1, not 1.12.2.

The latest version of Minecraft Forge for 1.12.2 is 14.23.5.2854, and is the version I suggest you download and try.

Besides that, your issue is most likely due to not understanding how the Fusion Crafting system works.  You must start a craft in the Fusion Crafting Core before the Crafting Injectors will actually take RF from whatever is connected to it.
