### ISSUE TITLE
[1.12] <crash launcher when logging into your own server>

### ISSUE THREAD

**Issue by imofey** [brandon3055/Draconic-Evolution#1609]
hello, I have a problem with mods, and it consists in the fact that when I log on to my server, the launcher crashes and gives errors -1 or 1 below I will attach a list of failures, but friends are fine, please help
[crash-2022-01-10_13.56.15-client (1).txt](https://github.com/brandon3055/Draconic-Evolution/files/7845172/crash-2022-01-10_13.56.15-client.1.txt)

**Comment by FoxMcloud5655** [comment]
First of all, you're running Mohist.  Mohist and Magma have both been proven to break mods, and Mohist in particular promotes downloading unofficial builds of plugins and claims that the official sources are broken due to the plugin developers, when in reality it's due to their own code that doesn't follow standard Bukkit practices.  They also silently pass off their own plugins as official without giving any hint to the user that they are very much not so when starting up the server.

All of that aside, you're out of date.  You need to update Draconic Evolution and it's dependencies Brandon's Core, CodeChickenLib, and Redstone Flux API.  I extremely highly recommend getting off of Mohist and using mods like Oxygen or FTB to handle server permissions essentials-style commands.
