### ISSUE TITLE
[1.12] No Loot Table for Chaos Guardian

### ISSUE THREAD

**Issue by BryceMalloy** [brandon3055/Draconic-Evolution#1623]
I am trying to add loot to the loot table of the Chaos Guardian using CraftTweaker & LootTweaker. I populated all loot tables into a dump file via a command in LootTweaker and I noticed that Draconic Evolution does not provide any loot tables to modify. If anyone knows if there is another way to add loot, please help me.

**Comment by FoxMcloud5655** [comment]
The Chaos Guardian does not have a loot table because it doesn't spawn loot.

**Comment by BryceMalloy** [comment]
The Ender Dragon has a loot table, it does not spawn loot either.

**Comment by BryceMalloy** [comment]
Closing issue as I personally found a work-around

**Comment by FoxMcloud5655** [comment]
The Ender Dragon only has a loot table specifically because Mojang added it due to people complainimg that they were not being able to add custom loot.

The Chaos Guardian handles all of that via listening for a mob death event, checking if the mob was the guardian dying, then performing any after death actions.
