### ISSUE TITLE
Chaos Dragon fight issue

### ISSUE THREAD

**Issue by TheMadmanofChaos** [brandon3055/Draconic-Evolution#171]
Forge: 1448
DE: 1.0.2 Snapshot 5 Bugfix.

The Chaos Dragon's attack that teleports entities away from the island is able to teleport the Chaos ender Crystals, thus rendering the fight near impossible as the dragon will be constantly invincible.

**Comment by ponge77** [comment]
yeah right. my friend and I fought with that dragon for couple of hours last night but couldnt even give him a single damage. we all wore top tier draconic aromors with fully enchant books on slots plus fully enchanted top tier draconic weapons. I even used botania's most powerful remote projectile weapon but it didnt work either. If I didnt hv Last Stand II enchant with 500 experience level and regeneration II buff pendant, I should have been killed hundred times. we broke all the crstals on top of obsidion towers and found that the dragon gets mad when we cget close to the choas shard crystal pillars in centre bottome of the island which we cant break.

**Comment by brandon3055** [comment]
Thanks @TheMadmanofChaos that may explain an issue that was mentioned on the forum. Would have taken me a while to find that. 

@ponge77 Never use last stand on draconic armor. For some reason it renders the armor completely useless against high power attacks when you run out of xp. And you dont need it anyway because without it its almost impossible for you to die as long as the armor has power.
