### ISSUE TITLE
draconic bow modes

### ISSUE THREAD

**Issue by theboo89** [brandon3055/Draconic-Evolution#184]
currently, the mechanism for changing modes on the draconic bow is shift+Right click... i think it may be a better option to switch to shift+mouse scroll wheel so you can fire while flying down... i saw brandon actually have this issue in his recent video on the new chaos guardian... just a thought... thx

**Comment by brandon3055** [comment]
Im planning some changes to the bow in the not so distant future and that will definitely be one of them. Not sure if i will use your scroll suggestion because then if say you were hiding from something or shifting on the edge of a block and you tryed to change weapons you would have the same issue. I may just replace shift with a "mode change" key which you can bind to whatever you like.
