### ISSUE TITLE
I'm having major problems with this mod, and I don't know how to even explain it.

### ISSUE THREAD

**Issue by TheTenthDoctor95** [brandon3055/Draconic-Evolution#195]
Here is a link to a youtube video of my experience. The video is unlisted, so don't worry about it causing people to not like the mod. The problems start at 7 minutes in.

https://www.youtube.com/watch?v=1gfjQSZS7eI

**Comment by HyperionNexus** [comment]
Hmm, well based off of the fire not moving (not sure if you have that animation off) it might be that your computer can't handle it or not enough RAM is allocated. Also make sure DE is using the latest snapshot that came out a week ago or so.

I'm just a user of the mod so I'm not exactly sure what is what. The devs should be able to help though.

**Comment by GreatOrator** [comment]
So reviewed the video, what version of the mod are you using?  Do you have particles and animations off?  From the frame rate, really looks like tic lag interfered with the ritual.  Would be better if we had a log from the event, but it most certainly looks like what Hyperion mentioned that your computer may not be able to handle the pack you are playing.

**Comment by TheTenthDoctor95** [comment]
I have snapshot 8 version, i have all animations on minimal, and i havent realy had any ram problems with my current pack before this. And it only causes problems at the chaos guardian and trying to do the ritual

**Comment by GreatOrator** [comment]
My suggestion, turn on all particles and animations and record the ritual again so we can see what is happening.  Honestly looks like a memory and tic issue with your pc

**Comment by brandon3055** [comment]
Wow that is really weird... Im almost certain its got nothing todo with the ritual itself because i haven't really done anything to it since i added it a while ago and nothing like this has ever been reported before. 

It looks like as GreatOrator said it is all related to lag. When the ritual was running you must have had a significant amount of tick lag so the ritual actually finished client side long before it finished server side. So when it looked like the ritual was done infact it was actually still running on the server (The integrated server if you are playing singleplayer) I have no idea how you managed to get teleported back to your TARDIS but when you clicked the ritual again after coming back that canceled the ritual which was still running server side. The world unloading around you was a result of the game not being able to keep up with you moving between dimensions due to the lag (if you did not know your tardis uses a different dimension to create the "bigger on the inside" effect)  

No way to know for sure if thats exactly what happened but its a pretty good guess. If you decide to try it again you can monitor the games tps with the command "/forge tps" Normal tps is 20.
