### ISSUE TITLE
(SUGGESTION) EMC(BALANCED TO MODDERS STANDARDS(I HOPE.))

### ISSUE THREAD

**Issue by TheTruth77** [brandon3055/Draconic-Evolution#219]
i have a emc value suggestion, thetenthdoctor95 said in a previous suggestion to have the draconian dusts emc be set to 10000 emc, but once you have a good amount it becomes too easy to get items of that emc value, i myself have over 20 mil emc in my transmutation table, i know it it supposed to be hard to get but my suggestion is balanced to your standards, why not set the emc value to a VERY expensive amount, something like, here it goes, 10 MILLION EMC PER DUST, that is 10 times more expensive than a red matter block by the way, this will force people to continue to search for the comets for the ores, along with trying to get enough emc to actually get one dust. 
ps. i have the emc set to this number via the /setemc command in project E as a thought it was fair.

**Comment by brandon3055** [comment]
As far as i know there shouldnt be an emc value for drqaconium dust by default because EE has no reference to calculate it from.

And there is a very big issue with your suggestion and that is that emc goes both ways. So take this hypothetical scenario for example.
  
New player starting a new world goes to the nether for the first time and finds a draconium ore which drops say 3 dust. That player not has the equivalent of 30 red matter blocks worth of emc after lust a few minutes of game play.

Now dose that sound balanced?

**Comment by TheTruth77** [comment]
i understand sir, after all its up to you your the modder.

i have another question is the caos guardain suposed to take 5 hours to kill in survival(full inventory of draconic batteries and full draconic armour, with sword and bow)? just curious. i know it was too easy before but really five hours? i timed it, sorry if i am being rude.

**Comment by brandon3055** [comment]
https://youtu.be/JkDX4CNs1UE
