### ISSUE TITLE
Chaos Dragon

### ISSUE THREAD

**Issue by ratedremedy** [brandon3055/Draconic-Evolution#220]
I encountered a bug where the Chaos Dragon killed me with creative/godmod on. Unsure if it's intentional or there's a config for it, but I figured I would report it.

**Comment by wlhlm** [comment]
This is very much intended since the Chaos Guardian deals Void Damage, the only type that also applies to creative mode players.

http://minecraft.gamepedia.com/Damage#The_Void

**Comment by babyblasphemy** [comment]
My question is why are players in creative targeted in the first place? It isn't making the fight any harder. If a player decides to try to fight the dragon in creative mode, they already had the intention to cheat, and thus had the desire to not be killed. If they find out that creative doesn't protect them, they could easily spawn in a bunch of draconic gear and capacitors to protect themselves, but then they'd just be angry at the mod author for causing them extra work/grief. 
Add on the fact that servers use creative mode as a means to safely check out areas players have requested to be investigated, and you've just made a larger hassle for them too.
I'd understand if it was an issue of the limitations of the different kind of damage you can create, or just being plain difficult to code. But answers saying that you want players in creative mode to die because it is supposed to be difficult doesn't seem like a valid answer. I'd rather get a straight answer than a troll-esque one.
