### ISSUE TITLE
Step Assist only in multiplayer?

### ISSUE THREAD

**Issue by Psithief** [brandon3055/Draconic-Evolution#222]
I couldn't get the step assist to work, so I came to look at the code.

The only reference to step assist in this repository seems to have a multiplayer check surrounding it. I think the logic for single player is missing.

[src/main/java/com/brandon3055/draconicevolution/common/handler/FMLEventHandler.java#L62-L75](https://github.com/brandon3055/Draconic-Evolution/blob/39602a3288b1b242fe6f8a5a36fefe6bbe04259a/src/main/java/com/brandon3055/draconicevolution/common/handler/FMLEventHandler.java#L62-L75)

**Comment by brandon3055** [comment]
All player movement is handled client side weather your on a dedicated server or the integrated server thats why that code is client side only. I cant really say why it's not working for you but im pretty sure your the only one having this problem because this is the first i have heard of it. If you have the setting enabled the only thing i can think if is some other mod is conflicting with that feature.

**Comment by Psithief** [comment]
I'll look into it and get back to you.

**Comment by Psithief** [comment]
Possible conflicting mods are:

* Tinker's Construct
* Ender IO
* Magical Crops

Here's another player with the same complaint: [reddit post](https://www.reddit.com/r/feedthebeast/comments/3be2w9/help_highstep_on_multiple_shoes_not_working/csldnyv)

I'll make a copy of my world and eliminate mods until it works or I run out of mods.

**Comment by Psithief** [comment]
The conflicting mod is Magical crops.
