### ISSUE TITLE
Minor Armor improvement

### ISSUE THREAD

**Issue by RoyalBingBong** [brandon3055/Draconic-Evolution#23]
Just started FTB Infinity and got the basic Wyvern Armor.
Two things I recognized about the armor:
* Jumping out of sprint feels really wonky, since the jump slows you down significantly
* The Boots seem to drain RF even if you have other Items that prevent fall damage, e.g. Extra Utilities  Angel Wings

**Comment by brandon3055** [comment]
"Jumping out of sprint feels really wonky, since the jump slows you down significantly"

Yea thats something i find rather annoying aswell but i think its going to be a pain to fix.

"The Boots seem to drain RF even if you have other Items that prevent fall damage, e.g. Extra Utilities Angel Wings"

It actually uses a small amount of RF when you jump. (Such crazy jump height dose not come free)
