### ISSUE TITLE
Chaos dragon ritual

### ISSUE THREAD

**Issue by blacksythe** [brandon3055/Draconic-Evolution#230]
For servers that have a limited world size they quickly become extinct can a ritual be added to summon them again.

**Comment by brandon3055** [comment]
Because of the way they are coded such a ritual would also have to respawn the entire island which would be incredibly laggy. 

A possible solution would be to reduce the distance between the islands to something like 2000 blocks which is now possible via the config.

And there is really no reason to restrict the size of the end because as its a void world it uses very little disk space compared to regular worlds.
