### ISSUE TITLE
several suggestions

### ISSUE THREAD

**Issue by shadoxxhd** [brandon3055/Draconic-Evolution#250]
**chaos gear**
armor and weapons 1 tier above draconic. weapons deal void damage, the bow shoots chaos projectiles, tools can mine bedrock & have larger AoE, armor makes you even more invincible than draconic armor (immunity vs HP=HP-5 kind of things) for a larger energy cost, with a gigantic energy buffer (like 1T RF), chaos tier for energy core(chaos blocks) (extreme storage increase), and a VERY large, portable chest (like the golden bag of holding, but much larger (applied energistics-like inventory)).

**things to spend RF on**
idk, but apart from rftools no mod uses nearly as much RF as you can produce/store with draconic reactor/energy sphere. so adding some game-changing reality-distorting machines with extreme energy costs would give you something to aim for in the late endgame.

**enchantment inventory**
with many mods adding enchantments, the slots on the draconic items are often not enough.

**sword of the dragon slayer**
requires 'condensed chaos cores' or something, counters draconic armor

**non-OP mode config setting**
configurable draconium worldgen&drops (so you can make draconium exclusive to some otherwise worthless planet), make dragon drop broken heart which needs extra items (minetweakable) before being able to make awakened draconium, higher energy consumption on everything, nerfed wyvern&draconic tools/armor (you'll need chaos gear for invulnerability/big AoE/high % damage)

**Comment by brandon3055** [comment]
Check out the upgrade system in the latest beta build. 

Regarding the chaos gear idea i dont plan to add a separate armor set BUT i do wont to add some sort of ritual that allows you to infuse draconic tools and armor with chaotic energy and that would then allow you to upgrade them using chaotic cores. 

I agree i do really need something that can use all that RF... I have a few ideas but nothing good yet.

The new upgrade system kinda takes the place of enchanting. Infact i was considering removing the enchantment system altogether but decided to leave it in for specialty enchants added by other mods.

Its now possible to defeat the draconic armor using a heavily upgraded staff of power or some other extremely powerful weapon but it will still be a hell of a fight.

A "non-OP" mode sounds like a good idea but would be a lot of work. It may have to wait till 1.8-1.9 because that update will already be a pretty big rewrite anyway.

**Comment by Alexismachina** [comment]
a large hydro collider to make resssources ? or matter to go down the road ?

**Comment by shadoxxhd** [comment]
once you got a 500x500 blocks silk touch ender quarry running, you have *too many items* (pun intended)... maybe we need some sort of inter-mod balance consortium :D
that aside, that hydro collider thingy seems like a good idea.<br>some stationary defense systems could also work well (maybe visually like the defense towers in paragon) - projecting the energy beams from the laser system into damaging plasma bursts. <br>destroying the chaos crystal could trigger some sort of demon invasion, making good defense systems necessary (or you could trigger the invasion yourself to get some rewards, sorta like the old invasion mod). 
maybe by fully charging a tier 10 energy core (w/ chaotic blocks) you could open a portal to another dimension, not following the rules we are used to (you could basically implement nearly everything you can imagine for that dimension; after some extremely hard, flashy/surreal boss fights you'd come back with some blueish glowing gear that still resides partially inside its origin dimension...)

**Comment by GreatOrator** [comment]
In regards to draconium world gen...it supports using cofh if installed so you could at least increase generation in a specific dimension if you want.

**Comment by shadoxxhd** [comment]
i want to disable the worldgen in all dimensions but one specific endgame planet (galacticraft)
