### ISSUE TITLE
Hill Step bug with half slab steps

### ISSUE THREAD

**Issue by iPlain** [brandon3055/Draconic-Evolution#251]
When using Hill Step on the Draconic Boots, you cannot walk up a half slab onto a covered 2 high area if that area begins directly after the slab.

See screenshot for clarification. Green ticks mean it is possible to walk through that passage with the hill step boots, red cross means it does not let you pass

http://i.imgur.com/DKJKz8O.png

If it helps, vanilla has this same issue with soul sand (regardless if you have hill step boots or not), as seen in screenshot below.

http://i.imgur.com/uVUpr92.png

**Comment by brandon3055** [comment]
Both of those issues are actually caused by the exact same vanilla bug which unfortunately i dont know a good way to fix... Other mods that add similar hill step functionality have the same problem. 

The reason it happens is when you walk up to a block that is higher then the one you are standing on the game calculates that you can ascend 0.5 blocks to step onto that higher block which is perfect if the block is something like a half slab. but if you are standing on something like soul sand where the height difference is more like 0.1 blocks it still uses 0.5 blocks for the calculation and detects that if it tries to move you up 0.5 blocks you will hit the top of the door frame and therefor it wont let you through. 

The issue with mi armor is exactly the same because i am just increasing minecrafts step height from 0.5 blocks to 1 block.
