### ISSUE TITLE
[Suggestion] Hover mode (lock flight) keybind

### ISSUE THREAD

**Issue by p455w0rd** [brandon3055/Draconic-Evolution#264]
Okay, so you've implemented my Draconic Hoe suggestion =] (Thank You ^_^) So now I have another request. I haven't posted this issue until now for two reasons:

1) Most mod authors just shoot down suggestions so they can concentrate on bugfixes.
2) I really figured it would have been implemented by now.

I'm stuck using all but the best piece of Draconic armor because it's such a hassle to open the config GUI and click the "Lock Flight" button every time I want to enable/disable this feature. I'm stuck using the not-so-OP Flux-Infused Jetplate just for this feature.

P.S. I hope you get the cat issue resolved ASAP. I'd make a commit, but I'm not familiar with that library/API.. =P

**Comment by brandon3055** [comment]
OOps i meant to reply to this 4 days ago but must have git distracted by something...

Ok so my question is why do you use that feature? There was really only one reason i implemented that feature in the first place and that was because if you logged out while flying when you log back in you would no longer be flying and fall to the ground which would be a big issue if for example you live in a void world so i added that as a sort of safety feature.

I have since found a way around the original problem so now if you log out while flying you will still be flying when you log back in. This makes the feature fairly useless in my opinion.

**Comment by p455w0rd** [comment]
Vertical speed is decelerated while hovering, which can be a nice thing to have on the fly. With the jetpack, it's bound to my 'R' key and is probably the 2nd most used key (save for normal movement keys) that I use. I guess as far as DE is concerned, it's just nicer to have to hit 'R' once rather than to rely on constantly double-tapping the spacebar (this is just really obnoxious in my opinion). I understand if you don't feel like doing it dude. I just figured with the code for keybinds and hover via double-tap already implemented, it wouldn't be that difficult or take too much of your time. Thanks for taking the time to reply.

**Comment by brandon3055** [comment]
Hmm so what your really asking for is a hotkey that that dose the same thing as double jumping that just toggles creative flight on and off? That shouldnt be to much trouble to implement i will just leave it unbound so you can assign it to whatever key you like.
