### ISSUE TITLE
Big non-control spawn

### ISSUE THREAD

**Issue by Neuromantix** [brandon3055/Draconic-Evolution#274]
I have a 2 spawners - zombie and enderman on base (coordinates about 2000/ -1700). In world i see non-control spawn this mobs near zero coordinates. Part of crashlog http://pastebin.com/gWyYZj3u Last draconic evolution release.

**Comment by Neuromantix** [comment]
I read  #238 and remove MFR rednet cables (change on enderIO) - this don't help - a lot of mobs on near-zero coordinates.

**Comment by brandon3055** [comment]
That sounds like it may be the same as this issue #196 Which as it turned out was not DE. Unfortunately we never figured out what was causing the issue but it also occurred with vanilla spawners meaning it was most likely some other mod modifying spawning behavior or something. 

Also that crash you posted is something todo with ic2 not DE. It looks like something related to one of their custom sounds.

Edit: In fixing another bug i think i just solved this one. Turns out vanilla spawners actually spawn an entity client side at 0, 0, 0 when you place them.... This is a vanilla but. Yay! i found a vanilla bug!. 
But because my spawners copy some of the vanilla code they have the same issue. This will be fixed in the next release.
