### ISSUE TITLE
shield sound option *possible feature request*

### ISSUE THREAD

**Issue by m1jordanallen** [brandon3055/Draconic-Evolution#277]
Ive been looking everywhere for an option to separately turn down the shield from the draconic armor, or just simply disable it.  I have had no luck finding the option.  I love the mechanic, but that sound drives me up the wall on a server.  Every dungeon a group of us go into its just clank clank clank clank. Sure would love to turn that sound down or at least off.  

If I missed the option I do apologize and I did not see that option included in todays changelog :)  

*edit:  I do know that the player sounds lower it, I want player sounds high and shield off in this instance, some may want the shield simply lower.

**Comment by brandon3055** [comment]
Its not possible to disable/adjust without turning down the player sounds because its considered similar to the player hurt sound.

If you really want it gone your only option would be to open the Draconic evolution jar and ether delete ore replace the sound file. This will not affect your ability to connect to servers or anything like that. The only negative effect is if you delete the sound completely there will be an "unknown sound event" warning in the console every time the sound tries to play.

The sound can be found at:
Draconic-Evolution-1.7.10-1.0.2.jar\assets\draconicevolution\sounds\shieldStrike.ogg
