### ISSUE TITLE
Avaritia Sword of the Cosmos Draconic Armor penetration "Fix"

### ISSUE THREAD

**Issue by Leguan12** [brandon3055/Draconic-Evolution#283]
// I'm trying not to sound hostile, if I do, it isn't meant like that

Why exactly do you think the sword of the cosmos needed "fixing" ?
A weapon that's supposed to kill absolutely everything (including admins in gm1) has every right to bypass all armours including draconic. If you're preventing it from doing what it's supposed to be doing, at least make it configure-/toggleable...
(Or even cooler, make it an extremely expensive module/upgrade based on avaritias InfinityIngots - that'd at least make it require similar ressources and progression as the Cosmic Armor, wich originally was the only armor capable of stopping the Sword of the Cosmos)
I just think it should be the player to decide if they want the DraconicArmor to be on par with the Cosmic Armor regarding its' protective powers...Avaritia is OP, it's meant to be op, and everything it does can be toggled - so you shouldn't go and just prevent it from working the way it was originally supposed to work (Bypassing the vanilla damage system leads to the conclusion of wanting the damage applied to be immune to manipulation/prevention) without having the user decide that.

For instance I, as a modpack maker (and mod developer) am left with no other choice than to make the DraconicArmor comparably expensive as the Cosmic Armor due to it now being also able to prevent the Sword of the Cosmos (the supposed-to-be most powerful weapon in the pack I'm currently working on) from doing its' job. Otherwise all balance would be down the drain...

Tempering with such extremely powerful things can easily lead to massive balancing issues, especially if they can't be controled.

**Comment by Alexismachina** [comment]
The armor wasn't made to counter that sword, it's just the new shielding mecanic prevents it from instankilling you. Since the sword does 2 heart it does not break the shield. If it did a lot of damage like the Bane of Pigs it would probably one shot.(Unless you have a full capacitor) which puts you in last stand mode.

**Comment by Leguan12** [comment]
That's not the point, the point is that the sword by default bypasses all armor (including the draconic shield). v1.0.2a implements code that prevents that from taking effect (nullifies the sword of the cosmos custom damage event).
;)

**Comment by GreatOrator** [comment]
That is because he fixed the code to so that the shield blocks any type of damage so long as the shield holds.  This was not directed at your mod specifically, just damage in general.

**Comment by brandon3055** [comment]
Ok did anyone even actually read the damn change log? Or did you read **-added support for Avaritia's "Sword of the Cosmos"** Then immediately stop and start complaining? 

Well if you read the change log you would see that the support i added actually makes the swore EFFECTIVE against the armor. Due to the way that sword deals damage the shield mechanic made it completely broke it. the 1.0.2a update **FIXES** that issue and makes the sword extremely effective against draconic armor.

**Comment by Leguan12** [comment]
@GreatOrator Just for info: I'm not involved with avaritias development. I just know its' source code ;)

@brandon3055 No I'm not one to start complaining just after reading something in any changelogs.
I did actually read the DraconicArmor code  before posting here - though it was late and I was tired so I misread your event-catcher code - sorry for that. (That, together with the changelog made me think that you prevented the Armor-bypass and instead only made it effective against the shield)
Just tested it - two-hitting the shield looks balanced to me :)

Btw. Could you apply the same fix to the BedrockSword from RotaryCraft ? (by default it instantly destroys armors / drains them of all energy, and currently doesn't even make a scratch into the DraconicShield)

Again sorry for complaining without really testing anything / misjudging based on wrong information on my side.

**Comment by brandon3055** [comment]
Ok we all make mistakes infact i have been known to look at things i wrote during a late night and think OMG WTF? so thats perfectly understandable. I will look into adding support for the Bedrock Sword in the next release. Let me know if you think of any other weapons i should add support for.

**Comment by brandon3055** [comment]
Dose not looks like i will be adding support for the BedrockSword because DragonAPI will not run in a dev environment. All other mods i know that have this issue such as COFH mods for example also provide a dev version of the mod to get around this issue but Reika has neglected to do that for DragonAPI. So unless im forgetting something there is no easy way to install RotoryCraft in my dev environment.

**Comment by Leguan12** [comment]
As Rotarycrafts sorce is on github (though you're not allowed to use its code), I assume you need a deobf-jar for it to work as a reference in your workspace ? (wich the source can then be linked to)
If that's the case you'd probably want to take a look at this: https://github.com/Parker8283/BON2/releases
(It's a simple executable jar programm that allows deofuscation of any MCP-compiled mod, so it allows you to create deobf aka dev versions with only the release version as a base)

**Comment by brandon3055** [comment]
Thanks for that it looks like a useful tool. But the deobf jar is now throwing a SecurityException http://puu.sh/oltR8/c2393d07ba.txt I may be doing something wrong. You mentioned linking them to the sources on github? I do not need to ad them to the project permanently i just need them to load for testing purposes then i will remove them when im done. Unless you know what im doing wrong i think i will just have to do this the hard way. Write the compatibility code completely blind then compile the mod and test it outside the dev environment and hope it works first time (It almost never dose lol).

**Comment by Leguan12** [comment]
When you try to open a referenced deobf jar you'll wee an error stating that the source code can't be found, together with an "attach source" button. You can then select a folder containing the respective mods' source, wich will then be shown in your dev environment. This also 'installs' the mod, though if you don't have any code that's directly interacting with the referenced mods' source and only need it installed ingame, you can just throw that mod, together with CodeChickenCore into the mods folder (located at <YourProjectName>/eclipse (NOT the one in the <YourProjectName> folder!).

(When first installing CCC into your dev invironment it'll ask you to select an mcp config path - wich looks like this:  <USER>/.gradle/caches/minecraft/net/minecraftforge/forge/<FORGE_VERSION>/unpacked/conf )

**Comment by brandon3055** [comment]
Oh thats the problem DragonAPI is one of those mods that dose not work with CCC Thats what i meant when i said CoFH mods have the same issue but CoFH also provides a -dev version that dose work with CCC.

In any case i have already done it the hard way (Worked out easier then i expected) The bedrock sword now deals 50 points to the shield (dose not deal 50 to the player once the shield is down) but more importantly it adds an additional 10% to the entropy on top of that added by the actual damage.

Not as powerful as the infinity sword but i think thats fair since the the infinity sword is significantly more expensive.

**Comment by Leguan12** [comment]
Yes seems fair - the InfinitySword can onehit in creative whilst the bedrock sword "only" destroys armors instantly, so it being less effective (but still a lot more then a normal sword) is absolutely perfect :D

**Comment by GGothicRide** [comment]
hi would anyone here know if the sword of the cosmos can bypass pvp protection, meaning server pvp is off in server config

**Comment by covers1624** [comment]
@GGothicRide It would NOT bypass server configs, as the code that blocks pvp damage is player side not sword side. Also, please don't hijack other peoples issues, you can create a new one if you have a question, or hop on IRC #DraconicEvolution on esper.net

**Comment by GreatOrator** [comment]
locking
