### ISSUE TITLE
Item Dislocator Issues

### ISSUE THREAD

**Issue by zzApotheosis** [brandon3055/Draconic-Evolution#294]
I figured you would rather watch this and see for yourself, rather than reading boring old text.

https://drive.google.com/file/d/0B_wljXPJi507NHBkUVI2UmZVOUk/view?usp=sharing

I noticed two things about the Item Dislocator (Haven't tested the Awakened one):
1) It draws in items from further than what the tooltip suggests (more than 8 blocks).
2) It doesn't affect items while sneaking.

**Comment by GreatOrator** [comment]
The sneaking part was intentional and mentioned in the changelogs actually.  The range, well I will let brandon touch on that.

**Comment by brandon3055** [comment]
oh... Oops... looks like i mistook one of the variables provided by the items update method for the item's meta data when in fact it was the inventory slot the item is located in. Meaning if you have ether magnet in slot 1 its range will b 8 and if you have ether in any other slot its range will be 32. It seems when i did all my testing i had the wyvern magnet in slot 1 and the draconic magnet in slot 2 so everything seemed to work... Woops...

This will be fixed in the next release. Which i was planning to release rite about now... Im glad i took one last look at the issues lol.
