### ISSUE TITLE
For @brandon3055

### ISSUE THREAD

**Issue by ArcasCZ** [brandon3055/Draconic-Evolution#305]
If you have wyvern / draconic armor and enabled Shield display, then Rei's minimap get glitched (img bellow).

Version of DE: actuall.

Images: https://ctrlv.cz/shots/2016/04/30/88aP.png , https://ctrlv.cz/shots/2016/04/30/gqfM.png

And please, @GreatOrator - don't mind that.

**Comment by brandon3055** [comment]
I dont see anything on my end that would cause this issue. I will look into it when i have time.

**Comment by brandon3055** [comment]
I currently can not find a legitimate website from which to download Rei's minimap for 1.7.10.

**Comment by ArcasCZ** [comment]
http://www100.zippyshare.com/v/HtILtp5r/file.html

Here is Rei's that we use.

**Comment by Alexismachina** [comment]
Honestly, i can't reproduce this.

**Comment by Alexismachina** [comment]
To be fair , you would have better luck using journeymap...

**Comment by brandon3055** [comment]
To be clear. When i said "legitimate website" i meant ether Curse or Minecraft Forum. Whichever the author/porter uploaded it to.. I will not download a mod from an illegitimate website and i will not download mods from random file sharing sites.

**Comment by ArcasCZ** [comment]
There is no official download, 'cause author abandoned it. But that's not reason to let it be.

**Comment by brandon3055** [comment]
I made some minor tweaks in this version which may or may not fix this issue. The changes i made shouldn't really effect anything because it was something that any renderer should take into consideration. But if it fixes the issue Great! If not there isnt much i can do. Even if i did have the mod to test with there really isnt anything else i can think of on my end that would cause this.
http://minecraft.curseforge.com/projects/draconic-evolution/files/2297668

**Comment by ArcasCZ** [comment]
Still appears - depends on Shield Display (Toggle Hidden). Also map shows when I open chat and Shield Display disappears.

**Comment by GreatOrator** [comment]
As brandon said:

But if it fixes the issue Great! If not there isnt much i can do. Even if i did have the mod to test with there really isnt anything else i can think of on my end that would cause this.
