### ISSUE TITLE
Incorrect Energy Core Value Tier 7

### ISSUE THREAD

**Issue by HadesDurin** [brandon3055/Draconic-Evolution#323]
## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version:10.13.4.1614
* Draconic Evolution version: 1.0.2d

## Mod List or Mod Pack (include version)
...
Mekanism (9.0.1.270)
Computercraft (1.74)
Chichen Chunks (1.3.4.19)
Extra Utilities (1.2.12)
Thermal Expansion (4.1.2.240)
Thermal Dynamics (1.20.171)
Thermal Foundation (1.2.4.114)
Redstone Arsenal (1.1.2.92)
NEI (1.0.5.120)
NEIIntegration (1.1.2)
NEIAddons (1.12.14.40)
Morph Beta 0.92
Waila (1.5.10)
Big Reactors (0.4.3A)
Equivalent Exchange 3 (0.3.0.318)
Tinkers Construct (1.8.8)
...

## Crash report
Problem with filling of the Tier 7 Energy Multi Storageblock
Short Video of my setup and the issue:

https://youtu.be/t2KQTnPBvhU

As you have seen there is only 0,1% used of the 2.1TRF and the energy pylon is filled up with RF and does not transfer anything to the Storage block

**Comment by HadesDurin** [comment]
a few minutes ago i get the latest version of DE 1.0.2e
after updating to that version i make this short video:
https://youtu.be/qUAFp4QFpPw

additionally you can see that the message points back to an old verwsion of DE

**Comment by HadesDurin** [comment]
a few moments ago i get notified by a user on github, about some coding stuff.

here is what "SteelShot" wrote me:
> it wont accept more than 2.147B as that -2147483647 to 2147483647 is the max integer values, its not a bug it just does not know what to do with a larger number. If it was built using Longs the limit then would be 9223372036854775807,

I hope that helps to solve the problem with the multi storage block

**Comment by brandon3055** [comment]
I may have an idea as to what is going on here. As the other user said the max energy value supported by the RF api is 2147483647. To get around this i used a custom storage system that that tricks the RF api into working with larger values. The down side is that any machine attached to a pylon (or waila for that matter) will only ever see a max of 2147483647RF in the core even though there could be much more then that. I suspect the conduit you are using is detecting that the pylon has reached its energy cap and is therefor not supplying any more energy. All other conduits i have tested with dont have this issue because they rely on the pylon to tell them when it is full and dont actually check the current storage.

So i suggest you try a conduit from a different mod and see if that fixed the issue. 

p.s. I noticed you use computercraft. Just wanted to let you know the pylons have custom CC support so it is possible to read the actual amount of energy stored. The peripheral name is "draconic_rf_storage"

**Comment by HadesDurin** [comment]
i get that name as i attached and activate the wired modem to the pylon and i will try out other cables from diffrent mods. Thanks for the idea.

**Comment by HadesDurin** [comment]
after some cable changes, points out that you are right.
i will bring up this issue in mekanism to see if that cable behavior was intended.
