### ISSUE TITLE
Annoying Armor Sound

### ISSUE THREAD

**Issue by Tico256** [brandon3055/Draconic-Evolution#325]
Since the update, which added the new, cool shield mechanic, every time when someone hits me, the armor makes loud, anvil-like sounds. I even deleted the sound file inside the mod, because it gets really annoying, especially during boss fights, dungeons, etc. and for recording lets-plays.

Could you please alter this sound to make it less annoying?

Tico256

**Comment by brandon3055** [comment]
Yea i have noticed the sound is rather loud. Turns out i had it set to 10X (1000%) for some reason. It will be set to the proper volume in the next update and should properly respect the player sound slider. I cant say exactly when i will release a new 1.7.10 build but until i do what you are doing now should not cause any issues.
