### ISSUE TITLE
Crash upon player connecting

### ISSUE THREAD

**Issue by GreatOrator** [brandon3055/Draconic-Evolution#344]
## Description
Player attempts to connect to server with outdated version of Draconic Evolution kicks other players from server. Looks like connecting with 1.02f when 1.02g is installed is causing the crash

## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: 1566
* Draconic Evolution version: 1.02G

## Mod List or Mod Pack (include version)
TolkienCraft II 2.9.2
## Crash report
http://pastebin.com/0MqegU7f

**Comment by brandon3055** [comment]
Sp your saying when a player tries to connect with 1.0.2f it kicks other players off who are using 1.0.2g? That really makes no sense. The server should not allow a player to connect with an outdated version and that is exactly what the log you posted is showing. It shows a player being rejected because they do not have 1.0.2g. It also looks like extra cells is missing or outdated on the client.

**Comment by GreatOrator** [comment]
well, EC and DE were both updated between 2.9.1 and 2.9.2, the log is what was given to me by the server admin.  I have heard of errors like this before so figured legit.  Have not replicated myself yet though...been at work.
