### ISSUE TITLE
Please Help if u can

### ISSUE THREAD

**Issue by MRGanboo** [brandon3055/Draconic-Evolution#358]
## Description
this isnt a issue sorry if im wasting your time u can just ignore this but im making a shop on my server with 15 players mainly friends so they can buy souls but i dont know how to give the players the different types of souls since i dont know their ids can u give me like a example for a mob like endermen?
## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: 1614
* Draconic Evolution version: 

## Mod List or Mod Pack (include version)
...
FTB Infinity Evolved v2.5
...
again sorry for wasting your time i know ur busy but i was really lost and i asked in other places and i found no answers if u end up answering thank you and also sorry for the bother again hope u have a great day / night

**Comment by shadoxxhd** [comment]
the souls don't have 'IDs', but a NBT tag that contains the internal entity name (the name you use in the /summon command).

**Comment by MRGanboo** [comment]
so how do i write the string like /give Name DraconicEvolution:mobSoul 1 0 {idk what goes here}

**Comment by GreatOrator** [comment]
Please make sure to do a search before asking questions next time...took me 1 minute to search closed issues:

https://github.com/brandon3055/Draconic-Evolution/issues/285

**Comment by brandon3055** [comment]
Because it may be useful to people here is a list of all the entity names
Note. This is copied directly from the entity registry so some of them are not valid entities that can be spawned.
Also note that for wither skeletons you also need to add the tag SkeletonType and set it to 1

Item
XPOrb
AreaEffectCloud
ThrownEgg
LeashKnot
Painting
Arrow
Snowball
Fireball
SmallFireball
ThrownEnderpearl
EyeOfEnderSignal
ThrownPotion
ThrownExpBottle
ItemFrame
WitherSkull
PrimedTnt
FallingSand
FireworksRocketEntity
SpectralArrow
ShulkerBullet
DragonFireball
ArmorStand
Boat
Mob
Monster
Creeper
Skeleton
Spider
Giant
Zombie
Slime
Ghast
PigZombie
Enderman
CaveSpider
Silverfish
Blaze
LavaSlime
EnderDragon
WitherBoss
Bat
Witch
Endermite
Guardian
Shulker
Pig
Sheep
Cow
Chicken
Squid
Wolf
MushroomCow
SnowMan
Ozelot
VillagerGolem
EntityHorse
Rabbit
Villager
EnderCrystal

**Comment by cKrijgsman** [comment]
for newer versions to spawn wither skeletons instead of SkeletonType now EntityTypeID should be set to 1

so:
give @p draconicevolution:mob_soul 1 0 {EntityName:Skeleton, EntityTypeID:1}

**Comment by amigo127** [comment]
it does not work in 1.10 how do. I want spawn a wither skeleton

**Comment by Prototype273** [comment]
Real quick for anyone still looking for the Wither skelly soul, the command is;

give @p draconicevolution:mob_soul 1 0 {EntityName:Wither_Skeleton, EntityTypeID:1}

**Comment by FoxMcloud5655** [comment]
Also, please note that the above command is for 1.7.10, not for 1.12.2.

For 1.12.2, type:
`/give @p draconicevolution:mob_soul 1 0 {EntityName:minecraft:wither_skeleton}`

**Comment by MrSkips** [comment]
> Real quick for anyone still looking for the Wither skelly soul, the command is;
> 
> give @p draconicevolution:mob_soul 1 0 {EntityName:Wither_Skeleton, EntityTypeID:1}

IM still having problems with this command. Im in FTB Infinity Evolved on the Twitch modpack.

**Comment by FoxMcloud5655** [comment]
Show us what command you're using, then.

**Comment by discoveryspace** [comment]
for FTB Infinity Evolved 1.7.10 the command to get a wither skeleton soul is:

**Comment by discoveryspace** [comment]
/give @p DraconicEvolution:mobSoul 1 0 {Name:Skeleton, SkeletonType:1}
