### ISSUE TITLE
Wither stars dupe when killed with grinder 

### ISSUE THREAD

**Issue by FluffyHusky** [brandon3055/Draconic-Evolution#360]
## Description
When using your grinder for withers the wither get killed then get killed making 2 stars get dropped 
## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version:ForgeMultipart-1.7.10-1.2.0.345-universal
* Draconic Evolution version:Draconic-Evolution-1.7.10-1.0.2a

## Mod List or Mod Pack (include version)
...FTB Infinity dont know the pack version
list other mods being used
...

## Crash report
```
CRASH REPORT HERE
```

**Comment by brandon3055** [comment]
I am nolonger actively developing 1.7.10. But if i ever do another bugfix build this will be on my list.

That said this is probably not an issue on my end because the grinder has been used on withers in meany packs including infinity for a very long time now and this is the first i am hearing about this bug.
