### ISSUE TITLE
Soul not reading nbt

### ISSUE THREAD

**Issue by magnus97** [brandon3055/Draconic-Evolution#365]
## Description
While playing project ozone 2 me and someone else we tried to make it so we got even more op on a pack that is ment to be op and while erabus erebus.animatedBlock (unlocalized name) have the block stored in nbt i saw that the souls did not get the right block since i saw in the file that it can't read nbt data for the mob so it was always spawning stone as it type and not what we wanted to be like Compresed Gaia Block and such so if you could make it so it would capture the right data for the mob.

## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: 10.13.4.1614
* Draconic Evolution version: 1.0.2h

## Mod List or Mod Pack (include version)
to many to list on github go here https://mods.curse.com/modpacks/minecraft/244939-project-ozone-2-reloaded

## Crash report
None since it does work in a way

**Comment by GreatOrator** [comment]
The issue here is that erebus apparently has them coded as blocks and not entities which is what is required for the souls to work correctly.  I would suggest contacting the dev of erebus to work out his code instead.

**Comment by brandon3055** [comment]
The real issue with saving the entity data to the soul is that it opens up too much potential for dupes. Example: You could give a zombie full draconic armor then kill it. It may take a few attempts but you could eventually get the zombie to drop its soul. You could then make a zombie spawner that would allow you to infinitely dupe draconic armor because the zombies would spawn wearing the armor and they would drop it on death.
