### ISSUE TITLE
[1.10.2] moving HUD location dosent actually move

### ISSUE THREAD

**Issue by Morpheus1101** [brandon3055/Draconic-Evolution#381]
Build *.93 on Forge *.075 using the mod on the MMD Dev Server

When in the Configure GUI i moved the HUD Display to the left hand side above the Shield Display and when exiting back to the main screen it is still on the right hand side

**Comment by brandon3055** [comment]
Wait... So you can move the displays while in the config screen and they stay where you leave them but they reset to their original positions when you close the gui?

That sound rather odd because the very fact that you are able to move them at all means there position is being updated. The only thing i can think of that would cause them to reset to their original positions would be if the new positions were not being saved to disk but even in that case their positions would only reset when you restart the game... 

Any tips on how to reproduce this?

**Comment by Morpheus1101** [comment]
This seems to have fixed itself when i re-installed the latest vers of the MMD pack from scratch.
