### ISSUE TITLE
Staff of power losing stats

### ISSUE THREAD

**Issue by AlphaWHH** [brandon3055/Draconic-Evolution#400]
Draconic Evolution 2.0.0.101
Forge: forge1.10.2-12.18.1.2092

Staff of power does not maintain the 1750 attack power that it had when it was created and upgraded to Draconic levels on RF capacity, Attack Damage and Attack AOE. 

After It was upgraded, it did a lot more damage to the ender dragon. Now It does as much as my overpowered Katana from Silent Gems with sharpness V and attack damage of 20.

It can no longer one hit an enderman, I thought that the draconic weapons were supposed to be strong.

**Comment by ilordnightmarei** [comment]
the power does seem a bit off along with slow attack speed

**Comment by brandon3055** [comment]
Oh.... Um... Oops. Seems i left in some debug code that sets the base attack to 1000 whenever the upgrade stats are read. it is not supposed to be that powerful. Its base attack damage is 60 which will one hit an enerman if fully charged and it can be upgraded to 105. I added the long cooldown time based on the new mc mechanics. I figured if an axe is slower than a sword because its heavier than a giant heavy staff should be even slower. 

And i did nurf pretty much everything a bit because there were too many complaints about DE being too op. But to make up for that i made all of the tool stats (including swing speed) configurable so if you dont like the defaults you can change them.

**Comment by AlphaWHH** [comment]
That seems more like a "lesser staff of some power".

Where can you change the swing speed in game?

**Comment by brandon3055** [comment]
Its not an in game config. You need to set it in the config file (Smaller number = faster swing)

**Comment by ilordnightmarei** [comment]
makes sense i can live with a slow attack speed on that notion of it being heavy  but aren't staffs light  i still think it looks like a battle ax XD

**Comment by brandon3055** [comment]
Yea... I think i may change the speed to 3.0 just because its the staff of power. Thats slightly faster than the draconic axe.
