### ISSUE TITLE
Celestial Manipulator has "jiterry" animation

### ISSUE THREAD

**Issue by HyperionNexus** [brandon3055/Draconic-Evolution#437]
Unlike the [video](https://www.youtube.com/watch?v=Y2iCiAW_RTg), the animation jumps forward (same for the sun/moon). I'm not sure if this is intended.

Version: 1.10.2-2.0.3.137

Edit: Once in a blue moon it has a normal animation for part of the cycle but it eventually begins to skip again within that cycle.

**Comment by brandon3055** [comment]
Are you standing within visual range of the manipulator? Also is the manipulator animation smooth?

**Comment by HyperionNexus** [comment]
I am within 10 blocks of the manipulator. The blue and orange spheres orbiting each other is smooth, just the sun and moon spheres are jumping forward (same for the actual sun and moon in the sky).

**Comment by brandon3055** [comment]
Odd... Sounds like for some reason time is not being adjusted client side which means the only thing updating the sun position client side is the vanilla time update packed which is only every second or so resulting the the jumping you are seeing. I will have to look into that but first i will need to wind a way to reproduce it in dev because all of my testing worked smoothly.

**Comment by brandon3055** [comment]
I dont know if there is really anything i can do about this issue but i will keep an eye out for a fix.
