### ISSUE TITLE
2 Chaos Dragons in one place

### ISSUE THREAD

**Issue by SpellMaster20** [brandon3055/Draconic-Evolution#456]
I know there is the chat that states there are bugs so be careful but there are Chaos Dragons at one island XD That is too much to handle.... Just thought you should know

Cheers Spell_Master, running away from two Chaos Dragons

**Comment by SpellMaster20** [comment]
Ok Apparently it is more when the chunks unload and reload they don't seem to remember that there is a Dragon already there so it spawns a new one with chat text as well

**Comment by SpellMaster20** [comment]
http://imgur.com/a/r61Ln

*Runs away*

**Comment by brandon3055** [comment]
Thats very odd because the chaos guardian spawns when the middle chunk of the island is generated... That is also when the rings and the towers are generated. If you can and dont mind doing some debugging could you switch to creative mode (the theoretically shouldn't attack you in creative but save your inventory just in case)

What i would like you to do is go to the center of the island and change/place some blocks. Then fly away so the island unloads and then go back and see if the chunk has regenerated. Also while you are there see if the towers have more than 1 crystal stacked on them because if the dragon is spawning more than once they should to. 
One last thing. Take a look at the rings and see if they are generated properly or if it looks like it has generated multiple rings ontop of each other. Screenshots of all this would be great.

**Comment by SpellMaster20** [comment]
Yep you were right when the center chunk is unloaded it then reloads that chunk like a brand new. 
The test sign was regened and the crystals appear to have a lot of crystals below then that are not active. So you have the current one that is active and the many that have been generated on multiply times

https://imgur.com/a/8wGAf

**Comment by SpellMaster20** [comment]
Oh this is also on a server have yet to try single player but can do if you want.

**Comment by brandon3055** [comment]
That would be good thanks. I have not been able to reproduce this at all in dev...
Also can you check if other chunks besides the center are affected. I want to know it the chaos cryatal is somehow causing it.

**Comment by SpellMaster20** [comment]
Mod pack we are using currently is ftb lite slightly modified. Also in a single player world the island has generated normally with not bugs in it so I am going to go back to server and find another island and see if it is server issues or not.

**Comment by SpellMaster20** [comment]
Ok something I think is up with multiplayer... I found a new Island it generated correctly so that is good but now the chaos Dragon has disappeared but the chaos shard is still protected...

**Comment by SpellMaster20** [comment]
I will agree with you I can't reproduce the bug either. I have found two other island the first the dragon disappeared and the second the island generated correctly and there was only one dragon... This is so weird I have no idea what is happening...

**Comment by SpellMaster20** [comment]
Also I actually had it where a comet regened as well... So maybe it is just the server I am on but I have no Idea sorry...

**Comment by brandon3055** [comment]
Ok the guardian disappearing sounds like a bug on my end.
