### ISSUE TITLE
Holo display is useful. but not at the same time.

### ISSUE THREAD

**Issue by DaMetaEX** [brandon3055/Draconic-Evolution#470]
because you need to click the core to see it makes it dificult to actually utilize it. first off the visuals are ALL THE BLOCKS makes it hard to see where you have a block and where you dont. especially at higher tiers. If you did it more like how Creativerse does there build thing. You start with the core it shows the 6 blocks that you can places attached to it. then it would show what can be connected from there. Less clutter easier to build. 

SECONDLY. if you are missing a block your current system will not tell you where its at. if you press the activate button but it fails have that missing spot have a phantom/glowing effect so you can more easily find it.

**Comment by brandon3055** [comment]
I recently made a change to the build guide that makes it a lot easier to use. Basically the blocks are smaller and they are solid. And as you get closer to the core it strips them back layer by layer making it easier to see what you are doing. However it seems that the guide is currently broken and occasionally renders incorrectly making it very painful to use. This will be fixed in the next version. I will also make the guide blocks darker so its more obvious which ones are real blocks.

Also i will see about adding your "Missing block" suggestion but no promises.
