### ISSUE TITLE
Lootcore

### ISSUE THREAD

**Issue by WoofieQc** [brandon3055/Draconic-Evolution#471]
i will like to know if possible to disable the lootcore or something?

the magnet ( dislocation ) is useless right now with new draconic weapon with the lootcore when you mine

**Comment by brandon3055** [comment]
Ahh thanks for reminding me i need to make the magnet attract those. Will be in the next update.

**Comment by brandon3055** [comment]
Looks like there was also an issue with the core. Its supposed to throw everything into your inventory at once as soon as it drops (if it can) but turns out there was an issue which resulted in it inserting part of its inventory then waiting a second before inserting more. This lead to you sometimes not collecting all of the items as you mine.

**Comment by WoofieQc** [comment]
Yup when i mine everything get inside the core
