### ISSUE TITLE
Feature: Energy Core Animation

### ISSUE THREAD

**Issue by dovahkiin4991** [brandon3055/Draconic-Evolution#492]
In 1.7.10 the draconic reactor would grow if you put in more draconium it would be cool with the energy cores grew as you input more energy so when you first create it, its just a small ball but as you fill it up it grows until it reaches its max capacity.

**Comment by brandon3055** [comment]
That would not really make sense. First of all the reactors size is partially linked to the amount of fuel it has and also to its temperature. It expands because it is a giant ball of super heated plasma and plasma tends to what to expend as its temperature increases. The energy core on the other hand is a giant chunk of stone cold draconium with a redstone core.

**Comment by dovahkiin4991** [comment]
true but energy has effects on all things. Mabey not a growing ball but mabey it could show a color change or something as it fills. I don't know its just an idea to make it look cool.

**Comment by brandon3055** [comment]
It already dose. It goes from the light purple colour to a deep red

**Comment by brandon3055** [comment]
https://puu.sh/sTUQV/c685312894.jpg
https://puu.sh/sTUWq/e166f56253.png

**Comment by dovahkiin4991** [comment]
No I'm saying like within a tier not from upgrading between them. So as it fills it makes a signigant enough color change.

**Comment by brandon3055** [comment]
it is within a tier. Granted the colour change isnt extremely noticeable especially with the blue shield around the core but its enough.
