### ISSUE TITLE
Client Crash when trying to render....

### ISSUE THREAD

**Issue by ProsperCraft** [brandon3055/Draconic-Evolution#58]
When using an Ars Magica 2 Arcane Desconstructor to disassemble a resurrection stone a block is produced that crashes the client when it tries to render.

We suspect it is the Charged draconium block.

http://pastebin.com/pVyjQXZ5
http://pastebin.com/ejm2VqR4

**Comment by brandon3055** [comment]
Hmm... I can stop the crash but i suspect it is a bug in AM2 because it is creating a block if draconium with damage value 32767 which is the wiled card value for crafting recipes. It means that the recipe will accept any damage value. I suspect you would have a similar problem when deconstructing other recipes that have one or more items that can be any damage value. Although depending on how the item is coded it may or may not crash the game. If there is a blacklist for the Arcane Deconstructor i suggest you add  the resurrection stone.
