### ISSUE TITLE
[1.10.2-2.0.8.177] [low priority] crystal rendering when using jar launcher.

### ISSUE THREAD

**Issue by antitheta** [brandon3055/Draconic-Evolution#598]
launching the direwolf20 1.10 modpack using the curse option for jar launcher would cause energy crystals to have a problem rendering in JEI that would break the inventory screen, refined storage screen, and possibly similar screens. 

![2017-02-11_16 39 28](https://cloud.githubusercontent.com/assets/13157956/22857784/167c1bc2-f07a-11e6-9ace-9a053e6ac252.png)
mousing over any item in JEI seems to temporarily fix it. 
![2017-02-11_16 39 34](https://cloud.githubusercontent.com/assets/13157956/22857785/167d82fa-f07a-11e6-8269-54ce5cf142ba.png)
![2017-02-11_16 48 27](https://cloud.githubusercontent.com/assets/13157956/22857786/167ebdc8-f07a-11e6-979b-a5c08e54feb4.png)

I only have access to my computer, I can't verify that it is reproducible on other computers. it was reproduced on a freshly downloaded direwolf20 pack, and again when I updated that pack to draconic evolution 2.0.8.177. java version is 1.8.0.121 (64bit) computer is windows 7.

**Comment by covers1624** [comment]
Weird.. Something is seriously wrong with shaders.. From my understanding, DE uses shaders to generate the texture for the crystals runtime, not sure why thet are broken.. As for the see thru inventory stuff, i believe that another mod may be at fault, first can you try and reproduce this issue with only DE, BrandonsCore, CCL, and JEI. If the issue is not present i reccomend removing some mods one by one from the DE pack untill the issue goes away, shot of that i have some vaigue ideas on what is broken, i had similar issues with EnderStorage.

**Comment by antitheta** [comment]
still occurring on a freshly created profile using forge 12.18.3.2221 and those 4 mods

**Comment by covers1624** [comment]
Can i get your log please?

**Comment by antitheta** [comment]
not sure which one so here they all are for the 4 mod profile

fml-client-1: http://pastebin.com/KbF4jSvp
fml-client-latest: http://pastebin.com/1Ntp7QCQ
fml-junk-earlystartup: http://pastebin.com/PEvhRB8i
latest: http://pastebin.com/1tUDjZh0

**Comment by brandon3055** [comment]
Does this still happen in the latest version?
