### ISSUE TITLE
[Request] More options for Draconic Armor under "stat tweaks" in config

### ISSUE THREAD

**Issue by TheBrain0110** [brandon3055/Draconic-Evolution#666]
Right now there's entries for tweaking Wyvern / Draconic tools attack damage, mine speed, etc. Great!

But there's nothing there about tweaking the armors; for example shield capacity, RF used per shield point, or shield recharge rate. Those would be nice to be able to play with too please.

Would you be able to add such entries in the config file for Armor stat tweaks? Thanks.

**Comment by LameGirlyCurly** [comment]
Yessir, please do allow tweaking the flight-speed - sure it's fun to have in singleplayer but will choke multiplayer faster you can say draconicevolution three times.

**Comment by brandon3055** [comment]
Not a bad idea but before i do this i really need to work on syncing configs between client and server because these options would be most useful for server admins but at the moment server admins cant use them unless they have the ability to also change them on all of the clients connecting to the server.

**Comment by brandon3055** [comment]
This will be in the next 1.12 release.

**Comment by TheBrain0110** [comment]
From what I can tell, you added the flight speed modifier, but not any of the original stat tweak suggestions like shield capacity or shield RF usage?
