### ISSUE TITLE
Crash when rendering with shaders.

### ISSUE THREAD

**Issue by NicosaurusRex99** [brandon3055/Draconic-Evolution#678]
I typed @Draconic in JEI and crashed with this hs err pid7256
https://pastebin.com/tapHaWWD

**Comment by covers1624** [comment]
Seems the JVM crashed in native code whilst attempting to render with shaders, try updating your graphics card drivers.

**Comment by NicosaurusRex99** [comment]
@covers1624 they are up to date, i even checked on intel's auto updater app and website

**Comment by NicosaurusRex99** [comment]
@covers1624 just a note, Draconic worked for me on windows 10, but when i downgraded to 7 (due to other reasons) it no longer works, i did test on other versions and i can render in items but the second i scroll JEI tab over it crashes

**Comment by covers1624** [comment]
JEI has nothing to do with this, This has to be purely due to your drivers being out of date or not supporting specific OpenGL flags, The last one seems like the most likely option. My guess, Intel dropped support for some parts of OpenGL on windows 7 so downgrading your drivers may be an option also.

**Comment by NicosaurusRex99** [comment]
ill report back if it works

**Comment by NicosaurusRex99** [comment]
3rd Generation Intel® Core™ Processors
With Intel® HD Graphics 4000, 2500

 
DirectX*	OpenGL*	OpenCL*	Shader Model Support	Intel® Quick Sync Video	Intel® Wireless Display	Intel® Insider™ technology	Intel® InTru™ 3D Technology	Intel® Clear Video HD Technology
11	4	1.2	5	Yes	Yes	Yes	Yes	Yes

**Comment by NicosaurusRex99** [comment]
it should support it tbh http://www.intel.com/content/www/us/en/support/graphics-drivers/000005524.html

**Comment by NicosaurusRex99** [comment]
@covers1624 i dont have optifine or shaders installed so is that title still accurate?

**Comment by covers1624** [comment]
Shaders is a broad term in 3d rendering. A shader can do both vertex transformations (moving things in 3d space) and fragment transformations (modifying colour, texture coordinates. ect..). DE uses a shader to Generate the texture used by the crystals, So yes the title is accurate. Most users define a shader as something fancy or an extera thing that happens / improvements, When in reality is just a really really fast way to do transformations, lighting and other post processing effects. Your Graphics chip can support almost always what the driver tells it to, If the driver does not fully support OpenGL due to windows 7 then you may be limited to what it can support because of the newer drivers not supporting windows 7, Getting your full launch log will also help as that prints out some data on launch about OGL.

**Comment by NicosaurusRex99** [comment]
will launch with just Draconic and JEI then send the full log

**Comment by NicosaurusRex99** [comment]
https://pastebin.com/5hScetzJ

**Comment by NicosaurusRex99** [comment]
@covers1624 ive just noticed #682 would me changing that setting "fix" my issue??

**Comment by covers1624** [comment]
Yeah, Disable shaders in DE's config.

**Comment by NicosaurusRex99** [comment]
Tried it, still borked

**Comment by covers1624** [comment]
Try with the new build brandon pushed not that long ago.

**Comment by NicosaurusRex99** [comment]
@covers1624 will try again

**Comment by NicosaurusRex99** [comment]
https://pastebin.com/pGmpcaHa
@covers1624 this is with latest build

**Comment by covers1624** [comment]
Can you launch the game with Mojang's Jar launcher so your log generates properly please?

**Comment by covers1624** [comment]
Or better yet, MultiMC. Mojangs new native launcher conflicts somewhat with FML's special formatting of log files, it also doesn't spit DEBUG or TRACE to the file for some reason..

**Comment by NicosaurusRex99** [comment]
MultiMC?!? ill launch the JAR but link to MultiMC pls

**Comment by NicosaurusRex99** [comment]
Log 1 JAVA 7
https://pastebin.com/k8np587P
Log 2 Java 8
https://pastebin.com/huD5uVj1
