### ISSUE TITLE
Console spam when Ender Dragon respawns/dies

### ISSUE THREAD

**Issue by tolly7654** [brandon3055/Draconic-Evolution#712]
As the title suggests, whenever someone respawns the ender dragon with the end crystals (and sometimes when it dies, the timing is a bit random), the console gets this error. Sometimes, a few times.

[17:22:55] [Server thread/ERROR] [draconicevolution]: WTF Is Going On!?!?!? The dragon is already dead how can it die again!?!?!
>  [17:22:55] [Server thread/ERROR] [draconicevolution]: Whoever is screwing with the dragon you need to fix your shit!
>  [17:22:55] [Server thread/ERROR] [draconicevolution]: Offending Entity: EntityDragon['Ender Dragon'/2075984, l='DIM1', x=-30.29, y=88.29, z=2.90] Class: class net.minecraft.entity.boss.EntityDragon
>  [17:22:55] [Server thread/ERROR] [draconicevolution]: ****************************************
>  [17:22:55] [Server thread/ERROR] [draconicevolution]: *  at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_333_DEEventHandler_onDropEvent_LivingDropsEvent.invoke(.dynamic)
>  [17:22:55] [Server thread/ERROR] [draconicevolution]: *  at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
>  [17:22:55] [Server thread/ERROR] [draconicevolution]: *  at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:635)

Is this intended? Or is it a problem?

We're running Sponge 1.10.2-2254-5.2.0-BETA-2264 if that helps.

-tolly765

**Comment by geminimiche** [comment]
Bump. Any ideas?

**Comment by brandon3055** [comment]
So first a little background on an issue this is related to. Basically someone is screwing with the dragon when it dies and causing its death event to fire every single time you hit it during its death phase. This is a very bad thing because it causes loot to be re dropped every time you hit it. As a temp fix i added a check to see if the dragon has already been killed before dropping loot and if it has i throw that error to the console. 

So you can pretty much just ignore this issue. Its caused by some other mod doing something it shouldn't and me stopping that mod from breaking DE.

**Comment by tolly7654** [comment]
Okay, that seems fair enough. Guess it's just our community constantly throwing their crap at the dragon and making our console logs 10MB bigger (one of our founders has a... not so great internet connection). Thanks for the reply brandon! 👍

**Comment by brandon3055** [comment]
I think i will silence that error in the next release.

**Comment by tolly7654** [comment]
That would be great for us. Thanks brandon!
