### ISSUE TITLE
Fusion Crafting not working

### ISSUE THREAD

**Issue by mybigfriendjo** [brandon3055/Draconic-Evolution#746]
Not seeing this issue here already makes me think this might be a problem on my side though i have done now what feels like everything i can possibly think of to get it working.

Fusion Crafting in 1.10.2 seems to be broken.
Exact Mod Version according to ingame Mod Menu 1.10.2-2.0.12.222

I created a completely new Pack on the Twitch Client consisting of Draconic Evolution Mod (plus brandon's core and codeChicken lib) and tried to get fusion crafting to work without avail. i used the generators provided in the pack to eliminate possible problems with other mods.

i have attached images of my attempts of crafting (i hope you can see the items in the background somewhat if not i'll gladly provide better images)

i double checked to make sure i used the right apples for the  upgrade thing (i used both versions minecraft provides) but also normal recipies seem to not want to work.

i'd love advice on what i am doing wrong - thx!

![2017-05-14_00 47 55](https://cloud.githubusercontent.com/assets/7951032/26029883/09a78814-3841-11e7-87d4-a3bd7dfe193f.png)
![2017-05-14_00 47 43](https://cloud.githubusercontent.com/assets/7951032/26029885/09aacbb4-3841-11e7-99ca-70233e529076.png)
![2017-05-14 00_43_11-twitch](https://cloud.githubusercontent.com/assets/7951032/26029884/09aa1430-3841-11e7-9357-d650a86d90a1.png)
![2017-05-14_00 39 11](https://cloud.githubusercontent.com/assets/7951032/26029886/09b29358-3841-11e7-8e82-34383cbf4183.png)

**Comment by GreatOrator** [comment]
how are you feeding it power?

**Comment by mybigfriendjo** [comment]
Draconic Generators in the back of each Pedestal with the front of the Generator facing away from the Pedestals. I got a stack of coal in each of them which i know is not enough power to complete the operation but it should at least let me start it should it not?

**Comment by mybigfriendjo** [comment]
for clarification
![2017-05-14_01 13 38](https://cloud.githubusercontent.com/assets/7951032/26029932/a051c0b2-3842-11e7-80e6-982ec6686e06.png)
![2017-05-14_01 13 40](https://cloud.githubusercontent.com/assets/7951032/26029933/a055ced2-3842-11e7-825e-29b301d878d4.png)

**Comment by GreatOrator** [comment]
Try turning around the furnaces so their back are against the crafters

**Comment by mybigfriendjo** [comment]
they are... as i said - the "face" of the generators is facing AWAY from the injectors. so the backside of each generator is connected to the injectors

**Comment by mybigfriendjo** [comment]
tried installing extra utilities with the creative energy sources... still no luck (chaotic injectors should work for infusing charged draconium blocks right?)
![2017-05-14_04 31 07](https://cloud.githubusercontent.com/assets/7951032/26030789/4f00d736-385e-11e7-8a0b-ed1052c04f7b.png)

**Comment by GreatOrator** [comment]
Well, what other recipes have you tried doing? Like have you used them to get the chaotic injectors?

**Comment by Joe4evr** [comment]
> (chaotic injectors should work for infusing charged draconium blocks right?)

Well, Charged Draconium doesn't exist anymore. 🙃 But yeah, Awakened Draconium is a Wyvern-tier recipe, so it should work fine. If you're in creative anyway,  have you tried DE's own Creative RF source? Have you tried just a single power source and running cable (or DE's energy lasers) into the injectors?

**Comment by mrossleslie** [comment]
This last update 2.0.12.222 has broken fusion crafting for me as well in SF3 survival. I'm using a full set of ten draconic injectors each powered with a dedicated flux point. This setup was working fine before the last update, however, now nothing works in regards to fusion crafting. I've tried the recipes for awakened core, arrow speed upgrade, and awakened draconium blocks and none appear to be valid in the GUI. I've tested in a creative world replacing all the injectors with the tier required for the recipe and still no dice. I'm pretty sure you can use the higher tiers for lower tier crafting.
![2017-05-14_07 31 03](https://cloud.githubusercontent.com/assets/7469816/26033750/57e321ce-3877-11e7-956c-31c2ef653456.png)

**Comment by mybigfriendjo** [comment]
The same happened to me after the mod-pack update (which featured the New De Version) though to make sure i created a new pack to confirm wheter it was DE or the pack. All my posts have been made while testing in the isolated World. @Joe4evr i tried multiple tiers of injectors and respective recipies that should work with them but to no avail. Start Button is nowhere to be found.

**Comment by mybigfriendjo** [comment]
@GreatOrator i was in creative to spawn in any Kind of injector as fusion crafting them doesn't work with the new version. I tried the recipie for the Basic to wyvern injector but that doesn't work either.

**Comment by mrossleslie** [comment]
Reverting back to 2.0.10.199 has fixed the issue; however is only a temporary solution.

**Comment by mindofaprodigy** [comment]
![2017-05-15_12 16 48](https://cloud.githubusercontent.com/assets/2769095/26067557/a6955e1c-3968-11e7-9250-dd32a544613e.png)
![2017-05-15_12 16 52](https://cloud.githubusercontent.com/assets/2769095/26067556/a6927e2c-3968-11e7-89f0-f018df86dfe8.png)
im also having issues with it not working in the 3.0.10 build of SkyFactory3

**Comment by SkippyMitch** [comment]
Same here, latest update broke stuff for me, I thought i was going crazy.

**Comment by Jonkar** [comment]
I have found the same issue. The set up is correct but it wont let me start. Has anyone found a fix to this yet, ? Version 1.10.2

**Comment by killerjerick** [comment]
Same issue, have the same setup that I used pre-update to make draconic armour, http://i.imgur.com/DaBsgmH.png http://i.imgur.com/0n3NhiA.png

**Comment by SkippyMitch** [comment]
The fix right now is to roll back to update 199

**Comment by anpilley** [comment]
I've got this in my game as well. A creative test world seems to work okay, but my server's getting the following in its log:

`20:53:04  [Fatal] Error executing taskjava.util.concurrent.ExecutionException: java.lang.NullPointerException at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_102] at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_102] at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]Caused by: java.lang.NullPointerException at com.brandon3055.draconicevolution.blocks.tileentity.TileFusionCraftingCore.getItemHandler(TileFusionCraftingCore.java:501) ~[TileFusionCraftingCore.class:?] at com.brandon3055.brandonscore.blocks.TileInventoryBase.getCapability(TileInventoryBase.java:204) ~[TileInventoryBase.class:?] at com.rwtema.extrautils2.utils.CapGetter.getInterface(CapGetter.java:139) ~[CapGetter.class:?] at com.rwtema.extrautils2.crafting.jei.JEIRadar$PacketPing$1.run(JEIRadar.java:133) ~[JEIRadar$PacketPing$1.class:?] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_102] at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_102] at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?] ... 5 more`

although it only shows up once, so I'm not sure if it's related.

**Comment by BloodWorkXGaming** [comment]
So a way to fix this issue is to move the crafting infuser further away than one Block.

only when The main block is 0 or 1 block away from the injectors it won't work.

**Comment by BloodWorkXGaming** [comment]
Reading a bit through the sourcecode, [this line states](https://github.com/brandon3055/Draconic-Evolution/blob/master/src/main/java/com/brandon3055/draconicevolution/blocks/tileentity/TileFusionCraftingCore.java#L195) that the distance between those two blocks has two be 2 or greater, that's why the setups above won't work.

**Comment by mindofaprodigy** [comment]
Hmm my setup worked in the previous version but I'll test and update when I get home

**Comment by mybigfriendjo** [comment]
i just tested it and indeed 2 air blocks of space do the trick. i could even accept this as solution for this issue myself though not sure if i should? it feels like 1 block should work as well....
please advise

**Comment by anpilley** [comment]
Curious. the version i had prior worked, as many people pointed out. Wonder if Brandon's just planning to change the animation, and wants more space for it or something.

**Comment by zakdel** [comment]
For whatever reason i am unable to get this to work either, using the SkyFactory3 mod pack. I have tried using previous versions of the mod pack itself, and of DE, i've tried increasing the amount of air blocks yet nothing seems to be working. Any ideas when we could expect an update?

**Comment by mybigfriendjo** [comment]
@zakdel could you post a screenshot of your setup? 2 blocks of air between the injector and the crafter did the trick for me.

not at home so i'll try a crude slice by slice view where I = injector, A = air and C = crafter
```
III | AAA | AAA | ACA | AAA | AAA | III
AIA | AAA | AAA | AAA | AAA | AAA | AIA
```
Make sure the injectors have direct view to the crafter. There can't be anything in between the injector and the crafter.

**Comment by ktole1999** [comment]
i tried steps listed above and could not get them to power up using eio conduit, mek power cable or drac gens on the back as depicted in the images.

**Comment by AndersWithTheCat** [comment]
I can also confirm on 2.0.12.222 that fusion crafting is how what bugged. its really a chance of like 1/100 if the setup will work. since i got a server full of people and some people got it to work but if a block is replaced it breaks again. some goea for setups that don't work then suddanly they do. Tested in Single player, a forge server and also a spongeforge server. all broken:) hope theres a fix to it soon

Played with the FTB Beyond Pack.

**Comment by Camrais** [comment]
I was really worried if my draconic evolution is broken or sth. Thanks for posting this with the two blocks distance now its working again!

**Comment by brandon3055** [comment]
Sorry about this. This was an unintentional change that will be reverted in the next release.

**Comment by dualmoon** [comment]
Note: this appears to be a visual bug. If I ignored it after starting the craft it eventually completed with no sounds or effects. Moving the injectors 2 blocks away fixes this

**Comment by cubedtear** [comment]
Same as @dualmoon here. Playing FTB Beyond (in case other mods matter). If injectors are 1 block away, it does not seem to work (it shows alright until you press Start, when the GUI becomes as if it wasn't crafting anything, and there is no animation in the world either), but it is crafting, and after a while, it produces the expected result. If injectors are further away, everything works as expected.

**Comment by trejkaz** [comment]
Does it really eventually produce the result? I've left this infusion injector in here for about 4 hours while I was out doing other things, and it is still sitting in the top slot. The lack of progress updates is what makes it hard to know...

**Comment by cubedtear** [comment]
In my case,  it did, after the normal time. In 4 hours it should have
finished... Maybe that is another bug?

**Comment by trejkaz** [comment]
Maybe. The progress goes straight to 100% as if it's working but then nothing happens.

It does work normally again after moving all the stuff further apart though, like with this bug, so I've assumed it's part of the same problem.
