### ISSUE TITLE
FPS issues / Energy Core

### ISSUE THREAD

**Issue by Fatthunder** [brandon3055/Draconic-Evolution#75]
******* Using Draconic Evolution 1.7.10 v1.0.1 RC 5

The energy core seems to be causing and having many issues at tier 7 (don't know about the other tiers).

The energy core causes massive fps issues from all parts of it (particle gens, core, energy pylon) with these active i go from around 100-120 fps to 40-60 fps.

The next problem is the energy core seems to reset every time I restart my game (resets to around 5B RF)

Also while less major the Draconic charger caues some fps issues, but no where clase to being as bad as the energy core.

**Comment by brandon3055** [comment]
Unfortunately there isn't much i can do about your PFS problem fancy renderers don't come without a cost. But the impact will vary from computer to computer. My FPS only drops by about 20 (from around 240) with no pylons.

However i am planning to build a custom particle engine to optimize my particles. And since most of the lag comes from the particles that may help (no guarantee).

Pro tip: You don't need more then 2 pylons. Each pylon has a practically unlimited transfer rate.

**Comment by Fatthunder** [comment]
Would you by any chance know what is causing the energy in the core to reset on restarting minecraft?

**Comment by Fatthunder** [comment]
another bug I forgot to mention is that with the Draconic Staff if I mine using AoE/Depth and then place a block back and try to mine it again it fails to mine it as if it becomes out of sync.  It will remove the block if you break an adjacent block within the AoE/Depth area.

**Comment by brandon3055** [comment]
Oh sorry. That i was not able to recreate. Was it a one off thing or dose it happen every time you close the game? And if it was a one off is it possible the game didnt shut down properly? If the game crashed or for some reason was not allowed to save the world any energy added since the last auto save would be lost.

Ans the staff problem sounds like it may be related to ghost blocks (blocks that are nos synced with the client) If it is you can right click any on the tools to re sync any ghost blocks around you.
