### ISSUE TITLE
Ender Energy Manipulator

### ISSUE THREAD

**Issue by Skardsen** [brandon3055/Draconic-Evolution#760]
I know this is a new item and I'm going to assume its still a WIP. Buttttt. Can anyone clarify where you're meant to click on the end portal (in the end). I have tried all I can think of. But maybe its just broken? I don't know. Just spits the "Must be placed on the end gateway." message.

**Comment by GizmoTheAssassan** [comment]
maybe the portal in the overworld

**Comment by Skardsen** [comment]
I've tried the overworld portal, the return portal, the island portals. I'm sure I'm just misclicking something.

**Comment by GizmoTheAssassan** [comment]
ok then i have no clue

**Comment by covers1624** [comment]
Place it where the egg usually spawns once defeating the dragon.

**Comment by brandon3055** [comment]
Hmm... what are the coords of the end portal in the end? Also is it still made out of bedrock? (Just checking mods have not changed things)

**Comment by Skardsen** [comment]
Playing SF3.

Standing on the pillar of the portal X:0 Y:0 Z:49. It's bedrock. And the first egg spawned on the top.

**Comment by brandon3055** [comment]
Ahh it should be around 0, 67, 0. Sounds like sky factory is moving the end portal...

**Comment by Skardsen** [comment]
Ahh, its no biggie for me, automated killing the dragon with mobGriefing off instead. Get a heart and egg that way.

**Comment by rjorgenson** [comment]
So just to confirm this item doesn't work in SF3?

**Comment by brandon3055** [comment]
it does not

**Comment by BabyJoshy** [comment]
ok just tried this on the newest 3.0.15 version, haven't tried on the others but to use this item u have to make a platform i used end stone for the enderman to spawn because its like the power (sacrifice) for it to work and u can set the ender energy manipulator on the rim on the portal like where u set the crystals to respawn the end dragon, or at the top middle, either one works, then just wait for it to kill a lot of ender men ( i guess around 100) does it pretty fast and then the dragon will come down and lay the egg as a item on the ground to pick up and repeat.
