### ISSUE TITLE
Draconic Rendering bug? 

### ISSUE THREAD

**Issue by NoplixDE** [brandon3055/Draconic-Evolution#779]
## Description
The title says it, idk if it is a config problem or an optifine problem or just and Draconic Problem but what I can say is, that the Draconic Version 2.0.10.199 worked flawlessly with all my other mods.
Doesn't matter what tier of Infusion, or what Dimension.  Always the same.
## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 12.18.3.2297 and 12.18.3.2316

## Crash report
No crash report just a video and it was made in the 12.18.3.2297 forge version, but the same happen if I updated. 
https://www.youtube.com/watch?v=lH8oyhp8jlU

**Comment by brandon3055** [comment]
I dont think its a rendering issue it looks line a sync issue the client does not know the craft is in progress for some reason. Odd because nothing has really changed as far as synchronization and i cant reproduce this in dev. Are you also running the latest BrandonsCore? 
Try without optifine and see if this still happens just to rule it out.

**Comment by NoplixDE** [comment]
It's fixed in dev so u can close this Issue :D
Sneaky question: Will u Updated it to 1.12? And when do you think :3

**Comment by brandon3055** [comment]
Will be starting 1.12 as soon as CCL is stable on 1.12.
