### ISSUE TITLE
Crash when using the Draconic Book

### ISSUE THREAD

**Issue by AnonymousPuppy** [brandon3055/Draconic-Evolution#8]
I'm using a custom modpack, forge .1240, and Draconic-Evolution-1.7.10-v1.0.0e.jar. A player on my server experienced a crash when he opened his Draconic book. This issue does not occur consistently 100% of the time, but it does occur.

Here is the crash report: http://pastebin.com/fZ3C1bQD

From the looks of it, it seems similar to the achievements crash I reported earlier. I can provide any additional information if necessary. Please fix this whenever possible, thank you! :)

**Comment by brandon3055** [comment]
From a crash report it looks like some sort of conflict between galacticraft and the mob soul renderer. I will look into it as soon as possible.

**Comment by AnonymousPuppy** [comment]
Looking forward to a fix soon, so I can update my modpack :)

**Comment by brandon3055** [comment]
It will probably be a while before i release 1.0.1 however the tolkiencraft mod pack gets a lot of pre-releases so i will let you know when it has a fixed version and you can just download the tolkiencraft pack and use its version.

**Comment by AnonymousPuppy** [comment]
Sounds good

**Comment by brandon3055** [comment]
Can you please test with the latest version of galacticraft because i think they may have fixed the problem.

**Comment by brandon3055** [comment]
I think i fixed the problem here is a link to my latest snapshot
https://drive.google.com/file/d/0B0fqrOj7BGp1ZndBcEVoV2pzazQ/view?usp=sharing
Please keep in mind this is a pre release version so there may be bugs. Please report any you find.

##Change Log##
-fixed spawner display mob shaking when disabled 
-removed energy cost for Draconic Chest flight
-added tool config gui
-safety flame can now be extinguished without breaking the block it is placed on
-removed a few leftover debug lines
-fixed teleporting between dimensions breaking NEI 
-added tool hud display
-implemented hud display in all configurable tools
-implemented hud display in energy core & stabilized spawner
-added option to rearrange locations in advanced dislocator 
-fixed galacticraft mob soul crash

**Comment by AnonymousPuppy** [comment]
Awesome, does this build fix this issue and the achievements crash as well?

**Comment by brandon3055** [comment]
yes thay were both caused by the same bug.
