### ISSUE TITLE
Energy Infuser crash on large NBT data

### ISSUE THREAD

**Issue by joral** [brandon3055/Draconic-Evolution#806]
## Description
I was using an RFTools storage tablet with a tier 2 storage module.  One of the contents was a full tier 3 storage module.  As soon as I added the storage tablet to the infuser,I was disconnected with the error listed.  This same exception would immediately happen as soon as I attempted to log back in.

## Base information
* Minecraft version:  1.10.2
* Minecraft Forge version:  12.18.3.2316
* FTB Beyond modpack version 1.10

## Crash report

https://pastebin.com/bQn2CJ2E

**Comment by brandon3055** [comment]
This is not a bug exactly... And not directly related to DE. That fact is that you have such an insane amount of data stored on that item that when the server tries to send the item data to the client so that it can be rendered in the infuser there is just too much data for the network to handle. The only way to fix this will be to remove the infuser or edit it to remove the item using MCEdit.
