### ISSUE TITLE
Draconic Evolution and Extra Utilities 2 crash

### ISSUE THREAD

**Issue by burakyl61** [brandon3055/Draconic-Evolution#820]
Hello I have an ıssues with draconic evolution and extra utilities 2 here the game log:
https://pastebin.com/f39tg5pV

**Comment by brandon3055** [comment]
Hmm... It looks like something is very broken in your mc instance but i have no idea what it could be. It looks like something is breaking both DE and Extra Utils. Can you give me any more info about the pack you are running?

**Comment by burakyl61** [comment]
I can upload config and mod folder files ıt's solves the problem?

**Comment by burakyl61** [comment]
Here the mod and config files;
https://mega.nz/#!HQo0WTIY

**Comment by burakyl61** [comment]
@brandon3055 hello are you there?

**Comment by brandon3055** [comment]
Due to security concerns we do not download or run random files provided by random users we do not know and trust. 
You have not given any info about your mod pack.
Is it a pre made mod pack or a pack you are building yourself.
Did this issue start after updating a mod? or did you just throw a bunch of mods together and find that it does not work?

I recommend you try some debugging.
First remove all mods from the pack and start adding them back until you figure out which mod causes the pack to break.
Start by adding BrandonsCore, Draconic Evolution and CCL
If the pack launches with those mods then install Extra Utils and try again.
If the pack still launches then the problem probably isnt ether of those mods.
Keep adding the rest of the mods one by one (Except in the case of mods with dependencies) until you find the mod that prevents the game launching.

**Comment by burakyl61** [comment]
Ok ı think problem with jei but ı don't know ok thanks it's again crash what can ı do? But ı try it thanks

**Comment by burakyl61** [comment]
Again it's crash :( I add BrandonsCore v2.1.9.113, DE v2.1.2.245, CCL v2.5.9.267 and CodeChickenCore v2.4.1.102 @brandon3055

**Comment by burakyl61** [comment]
ı build myself ı don't update mods by DE,BC,Extra utls

**Comment by brandon3055** [comment]
Are you saying it crashes with only those mods installed? If so try re downloading them. You may have a corrupt jar or something. 
Also keep in mind an issue tracker isnt an instant messaging service. You wont always get an immediate reply.

**Comment by covers1624** [comment]
A NEW crash report would be nice if you find an incompatability.

**Comment by burakyl61** [comment]
No it's again crash i download on curse but nope it's again crash and i sorry for not reply because i am not home for 2 days here it's crash log;

[crash-2017-07-05_12.58.17-client.txt](https://github.com/brandon3055/Draconic-Evolution/files/1124272/crash-2017-07-05_12.58.17-client.txt)

**Comment by darkmtbg2** [comment]
Try updating your java version or reinstalling the java. i could initialize the mods all fine and good so its likely to be somthing about the computer you are using and im at the start screen right now
do you have a secondary computer that you could attempt it on?
Im using the forge version of 1.2.18.3.2316 as the only thing that is different from yours

Testing with 12.18.3.2185 also does not throw a init issue

Enabeling all the other mods reveal an issue with redstone arsenal
