### ISSUE TITLE
Putting multiple filled applied energistics drives in draconic chest causing crash.

### ISSUE THREAD

**Issue by halacon** [brandon3055/Draconic-Evolution#850]
I was moving my applied energistics 2 computer and tried putting the drives into a draconic chest for transport.  The drives were full.  After the 8th drive went into the chest, I crashed to server select with the error message "Error: java.lang.IllegalArgumentException: Payload may not be larger than 32k bytes"  (I didn't copy the number down exactly)  I was not able to load back into the server as the message repeated.  After I was unable, I had my wife log in, and she crashed to server select with the same error.  The only fix was to roll the server back to the last save.  I tried it again to test and it again crashed.

## Base information
* Minecraft version: 1.10.2
* Mod Pack: FTB Beyond 

Unfortunately there was no crash report in my as it just booted me from server not fully shut down.

**Comment by ktole1999** [comment]
you can not put an inventory item inside another inventory item. same happens with AE2 drives, refined storage drives. you can safely transport them in your inventory. they will also crash if you put them in golden bags of holding.

**Comment by brandon3055** [comment]
Yea... Nothing i can do about this. The problem is that the items have such an insane amount of data stored on them that when you try to combine all that data in a single inventory minecraft just cant handle the insane amount of data. 
Mods that store that much data on a single item (DE included) really need to store that data in an external file system linked to the item.
