### ISSUE TITLE
Witchery death armor buggy interaction

### ISSUE THREAD

**Issue by tobi971** [brandon3055/Draconic-Evolution#857]
The witchery death armor, should when activated deal 15 % of max hp, absolute amor ignoring damage per hit ( https://sites.google.com/site/witcherymod/hand-of-death ) . 

If you now use this effect against the draconic armor, wich I find to be a legit counter, you can damage the player through the amor (the shield provided by the draconic armor stays unefffected but the health goes down), however you cant kill the player no matter how long you attack him. As soon as you have him down to half a heart the next hit will regenerate his hp, wich is really weird.

I think you should either be able to penetrate it entirely or not at all.

Minecraft 1.7.10
FTB Infinity Evolved 2.6.0

**Comment by brandon3055** [comment]
This is due to the way witchery is dealing that damage. They are just setting the players health value instead of actually attacking the player so there is no way for the armor to intercept this. 
When the player's health value is set to 0 the death event is intercepted by the armor and the armor realizes that the shield is still intact meaning that player should not have died so the death event is canceled.
