### ISSUE TITLE
1.12-2.3.2.258 - Chaos Guardian Crystal Crash

### ISSUE THREAD

**Issue by EPIICTHUNDERCAT** [brandon3055/Draconic-Evolution#864]
## Description
Crash while flying into Chaos Dragon Island! Seems like the error is in the (EntityGuardianCrystal.java:89)

## Base information
* Minecraft version: 1.12
* Minecraft Forge version:2443
* Mod Pack: Custom

## Crash report
https://pastebin.com/NwKwvXTg

**Comment by brandon3055** [comment]
This is ,a random issue that has been showing up since 1.10.2 and i still have absolutely no idea what causes it. For some reason the entity data manager sometimes returns an integer value when the value requested should be a float and that causes this crash.
This is on my bug list but for the moment i have no idea how to fix it. I will probably just end up building my own data manager at some point because vanilla's is just to problematic.

**Comment by EPIICTHUNDERCAT** [comment]
gotcha, just saw this. did you find out its forge?

**Comment by brandon3055** [comment]
Dont know if its forge. I just accidentally added the forge bug label

**Comment by ouroborus** [comment]
It seems like the a solution is to cast to `Number` and then use its functions to get the type you want. For example, [this line](https://github.com/brandon3055/Draconic-Evolution/blob/f85ad509cf7d81b4ec96f6fc6ded8b6d9c1fac22/src/main/java/com/brandon3055/draconicevolution/entity/EntityGuardianCrystal.java#L89) might be changed to:

    health = ((Number)dataManager.get(HEALTH)).floatValue();

**Comment by brandon3055** [comment]
Sure at this point i dont really see any other options. @covers1624 checked the bytecode for this and it looks like it should fix the issue.
