### ISSUE TITLE
Chaos Guardian spawning coordinate adjusting doesn't apply

### ISSUE THREAD

**Issue by T65536** [brandon3055/Draconic-Evolution#89]
Same as Title.

**Comment by brandon3055** [comment]
If your talking about the config option thats just for the spawned dragon.

**Comment by T65536** [comment]
How can I adjust that 10000 to 500? It give too many burden to server.

**Comment by brandon3055** [comment]
You cant. And it shouldn't cause any trouble for servers. It could be 500 or 500000 and it shouldn't make a difference because the end is void. Meaning nothing to generate and nothing to save. Unless you have something installed that adds structures to the end such as Hardcore Ender Expansion. but even then its still much less then a normal world.

**Comment by T65536** [comment]
Okay. Thanks for Answer.
