### ISSUE TITLE
[1.12] Energy Pylons do not support Forge Energy

### ISSUE THREAD

**Issue by ProxyPlayerHD** [brandon3055/Draconic-Evolution#895]
title says it all.
newest DrE version and newest IE version.

it is kinda hard to make a IE based pack with this and no TE to help out.
not even putting a Capacitor right next to an Energy Pylon will work.
why is it so incompatable, but using a IO Crystal works fine on both IE and DrE Machines?

**Comment by brandon3055** [comment]
Ahh i know exactly why this is happening! This is because IE only supports forge energy. Which by default is supported by all of my tiles however the energy pylon requires custom energy handling code so i does not inherit my default forge energy implementation. This should be fixed in the next update.

**Comment by ProxyPlayerHD** [comment]
awesome, thanks.
