### ISSUE TITLE
Draconic Energy Core not accepting flux power.

### ISSUE THREAD

**Issue by skillywack** [brandon3055/Draconic-Evolution#928]
Description: Before the most recent update, it was working perfectly. Afterwards, I cant connect it without using an energy conduit. It keeps saying the received energy is 0. 

Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 12.18.3.2477
* Mod Pack: FTB Presents SkyFactory 3

**Comment by brandon3055** [comment]
What do you mean exactly? Do you mean it works when you use conduits? What are you trying top connect to the core? What conduits are you using? Need more details.

**Comment by resinate** [comment]
flux points dont send power to the pylons, the plugs work fine. i also reported the same issue on their end as well

**Comment by brandon3055** [comment]
Last i checked that entire mod was completely broken. From the sounds of it it has not been fixed yet. I understand the attraction to that mod because it makes wireless energy so easy but when i last messed with it i found a tone of game breaking bugs.

**Comment by Cadens35** [comment]
Im test now and if u put some " Capacitor Bank " and conect a Conduit, the core receive energy normaly.

![image](https://user-images.githubusercontent.com/32654319/31360361-672a888a-ad24-11e7-9977-0a2f08bf9081.png)

**Comment by brandon3055** [comment]
@Cadens35 Are you also feeding your core with flux points?

**Comment by Cadens35** [comment]
> Are you also feeding your core with flux points? <

Yes sir. Flux point conected. Now im working in conect a Conduit Cable in the Core. When i finish this modification, ill post the Result. Sorry my delay.

**Comment by Cadens35** [comment]
The result:

Work if u conected a Conduit cable to feeding the Core.

![image](https://user-images.githubusercontent.com/32654319/31384010-9125897c-ad93-11e7-9c3e-16f23cf63c3d.png)

![image](https://user-images.githubusercontent.com/32654319/31384099-dae692a4-ad93-11e7-9c0e-ea4493b5f179.png)

**Comment by covers1624** [comment]
Yeah this is not an issue with DE, this is an issue with FluxedNetworks/FluxPoints.

**Comment by skillywack** [comment]
So, I also stopped exactly at 2.147 Billion RF on a tier 4 reactor. I think the plug is maxing out at a certain amount because if you use other energy transfer methods, it works.

**Comment by RickBlaine** [comment]
I'm having the same problem.   Using a Flux Point on a Tier 7 Energy Core, the Energy Core wont store more than 2.147 B RF (0.1%) .  I tried putting an ender io energy conduit between them but then I get no transfer at all. I get the same result if I put a capacitor between them.

**Comment by RickBlaine** [comment]
Its an issue with the latest DE.  Look at https://github.com/brandon3055/Draconic-Evolution/issues/924

**Comment by skillywack** [comment]
When I connect a flux point to the pylon, it doesnt work. But when I seperate the point and pylon with an Ender energy conduit, it works, but at the max transfer for the conduit (being around 26k RF/t). I'm thinking it is probably an issue with flux, so if anyone has ideas for a different wireless transfer that's easy to use, let me know.

**Comment by agent2153** [comment]
When i was using conduit i had the problem that it did not have enough capactiy for the amount of power i was producing. So i decided to use a dimensional transciever and create a new power network. Then i made it send and recieve it at the same time, then i had it output it to the pylon and input from the plux plug. I found this to work great i have had no problems since.
![untitled](https://user-images.githubusercontent.com/33132291/32068114-40fb2e10-ba7d-11e7-8c3a-dd646b6aee9d.png)
![untitled2](https://user-images.githubusercontent.com/33132291/32068115-4118c588-ba7d-11e7-8c18-2c6e0f2176fa.png)

**Comment by brandon3055** [comment]
@RickBlaine it's not an issue with DE it's FluxNetworks the best workaround for high throuput is ether crioducts or draconic I/O Crystal's

**Comment by Iz1cK** [comment]
Well... DE Pylons do not accept Flux points in my server... even tho in single player DE Pylons do actually accept rf from Flux points... this is confusing

**Comment by Lucas-Light** [comment]
**This is my workaround:**
Let's say we have a tier 8 core that stopped filling at 2.1B RF and we were using a flux network to fill it.
The issue is, that with the flux network you can't directly fill the core to go beyond 2.1B RF.

What you need to do is, make a second core that is big enough to hold the 2.1B RF which is a tier 4 core.
On the side of the **output** pylon from the **tier 4** core, you place a **Phantom Energyface** and connect that to the **input** pylon of the **tier 8** core.

This results in a transfer of 2.1B RF/t from the tier 4 core to the tier 8 core.
The tier 4 core can still be filled with flux points.
The tier 8 core can still output with a flux plug.

You could probably make even more tier 4 cores and do the same as above so you can increase the transfer even more.

**Comment by FoxMcloud5655** [comment]
This issue is years old...  Probably best not to necro it.  It's also for 1.10.2, which is currently unsupported, just so you're aware.

**Comment by Lucas-Light** [comment]
> This issue is years old... Probably best not to necro it. It's also for 1.10.2, which is currently unsupported, just so you're aware.

I have tested it on the Sky Factory 3 modpack
Modpack version: 3.0.22 (last updated dec-11-2021)
Minecraft version: 1.10.2
