### ISSUE TITLE
Draconic Charger Rendering bug

### ISSUE THREAD

**Issue by Keridos** [brandon3055/Draconic-Evolution#93]
When placing a draconic charger or dropping it (for placing you might need to go main menu and back in) and some blocks like the enderio experience obelisk or craftheraldry banners render wrong. See the squares on them, they are not supposed to be there.

Picture of it here: https://imgur.com/a/d36ow

**Comment by brandon3055** [comment]
Thats a bug i have been trying to figure out for a while. Its rather tricky because of the way renderers can interact with each other and cause weird effects.

**Comment by Keridos** [comment]
You do this: GL11.glDisable(GL11.GL_ALPHA_TEST); I think that might do the error, it looks as if the alpha channels are not turned on for these two other tileentities.

**Comment by brandon3055** [comment]
Yea that would make sense actually. Its been a while since i last tried to fix that and i have learned a bit more about GL11 functions since then. I will take another look at it soon and see if i can figure it out. But as its a very minor bug i will not be releasing a bugfix for it. Instead it will be fixed in 1.0.2.
