### ISSUE TITLE
Draconic wont power transfer_updated this issue into detail

### ISSUE THREAD

**Issue by joshuasuperboy** [brandon3055/Draconic-Evolution#930]
this is a issue with draconic evolution 1.12 universal 
I dont know how to take screen shots but when i try to fill the draconic fusion crafting injectors with RF they do not accept power like RF. I have tryed ender conduits to them but still they do not accept power. I tryed to reinstall the mod but they still did not accept any power. I even tryed to connect the creative RF sorce to the injectors and still no luck

**Comment by brandon3055** [comment]
First off this reply is aimed at everyone that opens issues like this not just you. 
This issue is completely pointless. It tells me absolutely nothing and i have no way of knowing what the problem actually is let alone how to begin to troubleshoot it. When opening a github issue you need to give as much detail about the issue as possible so i can actually attempt to reproduce the issue and figure out why its broken. I know for a fact that the fusion crafters work and accept power so there is probably something wrong with your specific setup but i have no way of knowing without some details about your setup. 

Some general rules when creating a github issue.

- If the issue is a crash always include the crash report and never paste it directly into github. Use a service like pastebin or gist.
- Give as much detail as possible not just "It does not work plz fix!"
- Provide screenshots of your setup if possible especially when dealing with multiblock structures.
