### ISSUE TITLE
Terrifying cacti

### ISSUE THREAD

**Issue by 23Link89** [brandon3055/Draconic-Evolution#942]
## Description
When wearing armor that provides shielding if you run into cacti it will completely decimate your armor in seconds

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 12.18.3.2511
* Mod Pack: Custom

## Crash report
```
CRASH REPORT HERE
``` N/A

**Comment by brandon3055** [comment]
Beware the cacti! THE GREATEST ENEMY OF THE DRACONIC!!!!! XD
This is due to the fact that there is no hit cool down on the shield so something like a cactus can hit you 20 times per second. 
This is an intended feature to make it a little easier to break though the shield. Fear of cacti was just an unintended side effect.
Will address this issue when i get around to re writing the shield mechanics.
