### ISSUE TITLE
[Suggestion] Item Dislocator and Solegnolia (Botania)

### ISSUE THREAD

**Issue by Lukas45** [brandon3055/Draconic-Evolution#947]
## Description
A suggestion to allow Botanias Solegnolia to block the drag from the (Advanced) Item Dislocator.
I requested the same for Reliquarys magnet some time ago, which was implemented (https://github.com/P3pp3rF1y/Reliquary/commit/6d4b08c27cda3ed3dd05963f2bf4414664fb8f66)

I know you have a magnet blocker of your own, but it is a tad expensive if you need to cover large areas, like your entire Conveyor Belt (IE) area.

**Comment by brandon3055** [comment]
I looked into it and it is probably doable but there is no simple way to do it without adding botania as a compile-time dependency which i dont really want to do for something simple like this. Especially since the functionality already exists in DE. 
As for IE belts i have added support for those which will be in the next release.
