### ISSUE TITLE
Issue using Draconic Tablet

### ISSUE THREAD

**Issue by Omega696** [brandon3055/Draconic-Evolution#96]
Hi, When I open the Draconic tablet I get the usual button for Index, clicking on it shows the index, but no further controls to scroll down the list of topics, or to change to another page. Backspace takes me to the title page. I have removed all texture packs, and restarted the game, as well as setting the GUI interface to small through auto to no effect. So far I have been using the copy of the manual you have up here and searching for topics, but would appreciate any help in getting the in game tablet to work.

**Comment by brandon3055** [comment]
You need to use the scroll wheel on your mouse to go up and down the list. If you dont have a scroll wheel i am going to add a scroll bar in a future update.

If you dont have a scroll wheel you should really consider getting a new mouse because i dont know how anyone could live without a scroll wheel...

**Comment by Omega696** [comment]
Ok cool, thanks for answering so quickly. Probably the only thing I didn't try. I actually use a DS4 gamepad mapped to use the keys due to issues with my hands because of M.E. I have the scroll mapped to the bumpers so sometimes forget to try that beyond scrolling up and down the hotbar.
