### ISSUE TITLE
Suggestion For an Automated Fuel System

### ISSUE THREAD

**Issue by VoidFyre** [brandon3055/Draconic-Evolution#988]
I would personally like to see a use for the fluid gate within DE.  If you could link that with a reactor and suck out a form of liquefied chaos and input molten awakened draconium, that would make for a very well made system.  As long as you supply it with the draconium, it would never run out of fuel.  As a result, you could keep a reactor running with a very large amount of chaos and a very small amount of fuel, and therefore have a reactor running constantly outputting millions of RF per tick.  I have noticed with testing that if you freshly refuel a reactor and remove all of the chaos, you have to almost start over with the regulation process and generate much less energy.  My reactor i have running on my survival server has a bit less than 40% fuel remaining and is generating a net output of 2,140,000 RF per tick.  Thats 2,300,000 that it's generating and 160k per tick the shield is using.  If i were to refuel it now and remove all the chaos, i would have to reset it and my net RF output would be near 200k per tick again.  
So, a system to automate removing chaos and adding draconium while the reactor runs would be an amazing addition.  

(ALSO ADD CHAOS ARMOR PLEASE, even though it would be OP as hell I want it for super endgame)

**Comment by brandon3055** [comment]
Chaos tier "everything" is planned for the next major re write of DE (which i have not had time to start yet) I may also look into a way of automating the reactors refueling process but it wont be as simple as you think. Based on the lore of the reactor the core is a ball of super heated Draconium plasma which at its core is hot enough to fuse into Chaos. It requires a powerful containment field just to keep it from destroying a sizable chunk of your world. So just imagine what would happen if you tried to remove some of that plasma from its containment field and store it in a generic tank... The results would not be pretty.

**Comment by HuJK** [comment]
But you can store chaos in generic chest, why not it can't store at generic tank? 

I guess we need to build a double layer containment field, and liquefied chaos need cool down before drain out, molten awakened draconium need to preheat to same temp as the core before fill in.

**Comment by FoxMcloud5655** [comment]
No, you can store Chaos Shards, not pure Chaos.  You're essentially taking Draconium and turning it into an unstable form of Chaos in order to generate RF off of it using the reaction.  What this would be doing is essentially taking this unstable Chaos and allowing it to cool down slowly, and (however brandon wants to make the lore for this happen) in doing so, it would turn back into Draconium, since that's what it started out as.  Either that, or piping this Chaos into a crystallizer and solidifying it fast enough would be a an extremely tricky process that would also result in world destruction if not handled properly.
