### ISSUE TITLE
pt_BR Translation

### ISSUE THREAD

**Issue by InterPlay02** [brandon3055/Draconic-Evolution#995]
Hello!

I've made a Translation for Draconic Evolution:
https://pastebin.com/27jitkzG
I was using the newest 1.12.2 version to make it.
I hope you could use it for the future releases.
But I want to ask you where I find the file to translate the Information Tablet.

**Comment by InterPlay02** [comment]
#EDIT Ive made some correction for the spelling. Should be fine now...
=)

**Comment by Tahakk** [comment]
There you go, not sure about translations since there is none other than english.

 [https://github.com/brandon3055/Project-Intelligence-Docs/blob/master/ModDocs/Draconic%20Evolution/draconicevolution-en_US.xml](https://github.com/brandon3055/Project-Intelligence-Docs/blob/master/ModDocs/Draconic%20Evolution/draconicevolution-en_US.xml)

**Comment by brandon3055** [comment]
The version of Project Intelligence that is currently in use by DE is a proof of concept that does not currently support localization. I am in the process of writing a new version of that mod that will support localization.

I will add your localization in the next update. Thankyou.

I will add your

**Comment by InterPlay02** [comment]
Ok, good to know.
Thanks. =]
