### ISSUE TITLE
performance issue 

### ISSUE THREAD

**Issue by JoeSGT** [brandon3055/Draconic-Evolution#996]
## Base information
* Minecraft version: 1.12.2
* Mod version: Draconic-Evolution-1.12-2.3.5.269
* Minecraft Forge version: forge-1.12.2-14.23.1.2565
* Mod Pack: (if applicable)

so the issue with draconic Staff of power when it mine 11x11 in the ocean start to cause the TPS to goes down about  between 1-4 TPS, and not just mining in the ocean but if you where to mine in land you can also lag the server the amount of drop there is. I was wondering if you can fix this by adding something like what avaritia has called Matter Cluster, It holds all mined items when you start to mine with a pickaxe in avaritia, more information about this matter cluster can be found here https://ftbwiki.org/Matter_Cluster

As for the ocean can you so how fix it ? or add a way to prevent them to mine in ocean or have a more control over the range of radius of the staff of power can mine, instead of 11x11

EDIT: 
here is more information about more lag issues
not only you can mine large amount but player can mine ore's that give out XP.
player can have a 11x11 Ore's that give out XP. that start to give more performance tps issues

**Comment by ktole1999** [comment]
dont use 11x11.

**Comment by JoeSGT** [comment]
there no config option to turn that lower the radius

**Comment by brandon3055** [comment]
Im sorry... What?
![](http://ss.brandon3055.com/wtyu9wa.png)
![](http://ss.brandon3055.com/0gq0sm2.png)

**Comment by JoeSGT** [comment]
@brandon3055  does not prevent player's from using 11x11
nasty players who want to harm can do it

**Comment by DumbSlayer** [comment]
as u can see here the loot core only works when mining  sideways https://gyazo.com/f6303bc2f86bc147580013a41555e03c

but when I try to mine forward it doesn't make the loot core https://gyazo.com/fdcbd13e5c40f0c7923209dc8ec84721

**Comment by covers1624** [comment]
Ah, see a gif is a thousand words. Another mod is causing DE to not receive events for items being dropped, causing the Loot Core to not spawn. Strip down your modpack and if you are on as sponge server, remove any plugins, untill the issue is resolved, there is literelly nothing on DE's end that could cause this to break its another mods fault.  
When the LootCore is spawned in the world, it has nowhere near the performance hit as actual items, it is essentially functionally equivelent to your example of Avaritia's Matter cluster, except the loot core throws the items in your inventory not the cluster itself.  
As for the ocean mining there is literelly nothing that DE can do to prevent this, if players (im assuming you are talking about a public server) spend hours upon hours grinding DE JUST to get a Staff and destroy the bottom of the ocean to lagg your server then thats an issue you have to solve with banning / temp banning and such, its not DE's job to administrate your server, You could even go as far to install a plugin to slow the tickrate of fluids, or even stop it all together. If you are talking about singleplayer then again its not DE's job to stop you from doing things that would obviously cause lagg, like mining bellow a desert and having sand fall or the bottom of the ocean, just don't do it in the first place. Theres soo many items / tools these days that have AOE abilities even IF something was added to DE, and it can't, then they would just use another tool.

**Comment by JoeSGT** [comment]
ah okay it does seem to be a spongeforge issue
Is that i never knew about DE having Loot Core
and i did some testing and and it seem to be an issue with just spongeforge
version i had tried uisng spongeforge-1.12.2-2555-7.0.0-BETA-2783
and it works haft and haft this is what i mean
![e8536ebe56f1feae263cf8cd39c3f5d4](https://user-images.githubusercontent.com/30296350/34191877-57977ce4-e518-11e7-9a7f-cc8ee40b395b.png)
