### ISSUE TITLE
Advanced Entity Detector, ItemStack Item Detection

### ISSUE THREAD

**Issue by ThomasAunvik** [brandon3055/Draconic-Evolution#998]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.5.269
* Minecraft Forge version: 14.23.1.2566
* Mod Pack: Direwolf20

## Description
Advanced Entity Detector. For The names of items are not appering as their itemname, but instead as ItemStack. But the entity names show up after selecting.

![image](https://user-images.githubusercontent.com/9968151/34132835-fb734b58-e451-11e7-9e00-7dea1b360a3a.png)
After clicking on them:
![image](https://user-images.githubusercontent.com/9968151/34132791-d3b9ebee-e451-11e7-9d1e-146c1cb74492.png)

## Suggestion
A suggestion to item detection would be that you can use the item unlocalized name to filter them out. That would make so much easier, and probably an entity search function, or a something like nearby item selection.

## Log Files
Part of Logs: https://pastebin.com/sQdhU7Kr Pretty suprised there is many exceptions in this log from this mod. (latest.txt)

Whole log file: https://gist.github.com/ThomasAunvik/11fb01ed74d52695a3b66445183d531a (not so useful)

**Comment by brandon3055** [comment]
This is probably something i should have thought of. Its not meant to be able to detect what item is on the ground only that there is some item entity on the ground. The problem is that lots of mods all add their own custom item entities which are specifically designed to be indistinguishable from vanilla's. I will have to add a special case check for those.

Those errors are from the Info tablet which is currently getting a re write.
